/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param objectIds
 * @param objectTypes
 * @param userIds
 */
data class ActivitySearchSubscriptionsRequest(
    @Json(name = "ObjectIds") val objectIds: kotlin.collections.List<kotlin.String>? = null,
    @Json(name = "ObjectTypes") val objectTypes: kotlin.collections.List<ActivityOwnerType>? = null,
    @Json(name = "UserIds") val userIds: kotlin.collections.List<kotlin.String>? = null
) {}
