/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param accessToken
 * @param expiresAt
 * @param idToken
 * @param refreshToken
 */
data class AuthToken(
    @Json(name = "AccessToken") val accessToken: kotlin.String? = null,
    @Json(name = "ExpiresAt") val expiresAt: kotlin.String? = null,
    @Json(name = "IDToken") val idToken: kotlin.String? = null,
    @Json(name = "RefreshToken") val refreshToken: kotlin.String? = null
) {}
