/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param keyID
 * @param label
 */
data class EncryptionAdminCreateKeyRequest(
    @Json(name = "KeyID") val keyID: kotlin.String? = null,
    @Json(name = "Label") val label: kotlin.String? = null
) {}
