/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param content
 * @param creationDate
 * @param ID
 * @param info
 * @param label
 * @param owner
 */
data class EncryptionKey(
    @Json(name = "Content") val content: kotlin.String? = null,
    @Json(name = "CreationDate") val creationDate: kotlin.Int? = null,
    @Json(name = "ID") val ID: kotlin.String? = null,
    @Json(name = "Info") val info: EncryptionKeyInfo? = null,
    @Json(name = "Label") val label: kotlin.String? = null,
    @Json(name = "Owner") val owner: kotlin.String? = null
) {}
