/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param exports
 * @param imports
 */
data class EncryptionKeyInfo(
    @Json(name = "Exports") val exports: kotlin.collections.List<EncryptionExport>? = null,
    @Json(name = "Imports") val imports: kotlin.collections.List<EncryptionImport>? = null
) {}
