/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/** @param propertyKeys */
data class EncryptionAdminListKeysResponse(
    @Json(name = "Keys") val propertyKeys: kotlin.collections.List<EncryptionKey>? = null
) {}
