/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param name
 * @param `value`
 */
data class IdmACLAction(
    @Json(name = "Name") val name: kotlin.String? = null,
    @Json(name = "Value") val `value`: kotlin.String? = null
) {}
