/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param description
 * @param lastUpdated
 * @param name
 * @param ownerUuid
 * @param policies
 * @param resourceGroup
 * @param uuid
 */
data class IdmPolicyGroup(
    @Json(name = "Description") val description: kotlin.String? = null,
    @Json(name = "LastUpdated") val lastUpdated: kotlin.Int? = null,
    @Json(name = "Name") val name: kotlin.String? = null,
    @Json(name = "OwnerUuid") val ownerUuid: kotlin.String? = null,
    @Json(name = "Policies") val policies: kotlin.collections.List<IdmPolicy>? = null,
    @Json(name = "ResourceGroup")
    val resourceGroup: IdmPolicyResourceGroup? = IdmPolicyResourceGroup.rest,
    @Json(name = "Uuid") val uuid: kotlin.String? = null
) {}
