/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param namespaces
 * @param operation
 */
data class IdmUpdateUserMetaNamespaceRequest(
    @Json(name = "Namespaces")
    val namespaces: kotlin.collections.List<IdmUserMetaNamespace>? = null,
    @Json(name = "Operation")
    val operation: UpdateUserMetaNamespaceRequestUserMetaNsOp? =
        UpdateUserMetaNamespaceRequestUserMetaNsOp.PUT
) {}
