/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param metaDatas
 * @param operation
 */
data class IdmUpdateUserMetaRequest(
    @Json(name = "MetaDatas") val metaDatas: kotlin.collections.List<IdmUserMeta>? = null,
    @Json(name = "Operation")
    val operation: UpdateUserMetaRequestUserMetaOp? = UpdateUserMetaRequestUserMetaOp.PUT
) {}
