/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param action
 * @param applyTo
 * @param key
 * @param `value`
 */
data class InstallHeaderMod(
    @Json(name = "Action")
    val action: InstallHeaderModAction? = InstallHeaderModAction.APPEND_IF_EXISTS_OR_ADD,
    @Json(name = "ApplyTo") val applyTo: InstallHeaderModApplyTo? = InstallHeaderModApplyTo.REQUEST,
    @Json(name = "Key") val key: kotlin.String? = null,
    @Json(name = "Value") val `value`: kotlin.String? = null
) {}
