/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param action Action can be Rewrite, Redirect, etc...
 * @param effect
 * @param matcher
 * @param `value`
 */
data class InstallRule(

    /* Action can be Rewrite, Redirect, etc... */
    @Json(name = "Action") val action: kotlin.String? = null,
    @Json(name = "Effect") val effect: InstallRuleEffect? = InstallRuleEffect.DENY,
    @Json(name = "Matcher") val matcher: kotlin.String? = null,
    @Json(name = "Value") val `value`: kotlin.String? = null
) {}
