/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param description
 * @param label
 * @param query
 * @param type
 */
data class JobsContextMetaFilter(
    @Json(name = "Description") val description: kotlin.String? = null,
    @Json(name = "Label") val label: kotlin.String? = null,
    @Json(name = "Query") val query: ServiceQuery? = null,
    @Json(name = "Type")
    val type: JobsContextMetaFilterType? = JobsContextMetaFilterType.RequestMeta
) {}
