/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.pydio.kotlin.openapi.model

import com.pydio.kotlin.openapi.model.ActivityObject
import com.pydio.kotlin.openapi.model.IdmACL
import com.pydio.kotlin.openapi.model.IdmRole
import com.pydio.kotlin.openapi.model.IdmUser
import com.pydio.kotlin.openapi.model.IdmWorkspace
import com.pydio.kotlin.openapi.model.JobsActionOutput
import com.pydio.kotlin.openapi.model.ObjectDataSource
import com.pydio.kotlin.openapi.model.ProtobufAny
import com.pydio.kotlin.openapi.model.TreeNode

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param acls 
 * @param activities 
 * @param dataSources 
 * @param event 
 * @param nodes 
 * @param outputChain 
 * @param roles 
 * @param users 
 * @param workspaces 
 */


data class JobsActionMessage (

    @Json(name = "Acls")
    val acls: kotlin.collections.List<IdmACL>? = null,

    @Json(name = "Activities")
    val activities: kotlin.collections.List<ActivityObject>? = null,

    @Json(name = "DataSources")
    val dataSources: kotlin.collections.List<ObjectDataSource>? = null,

    @Json(name = "Event")
    val event: ProtobufAny? = null,

    @Json(name = "Nodes")
    val nodes: kotlin.collections.List<TreeNode>? = null,

    @Json(name = "OutputChain")
    val outputChain: kotlin.collections.List<JobsActionOutput>? = null,

    @Json(name = "Roles")
    val roles: kotlin.collections.List<IdmRole>? = null,

    @Json(name = "Users")
    val users: kotlin.collections.List<IdmUser>? = null,

    @Json(name = "Workspaces")
    val workspaces: kotlin.collections.List<IdmWorkspace>? = null

) {


}

