/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param cells
 * @param link
 * @param node
 */
data class ListSharedResourcesResponseSharedResource(
    @Json(name = "Cells") val cells: kotlin.collections.List<RestCell>? = null,
    @Json(name = "Link") val link: RestShareLink? = null,
    @Json(name = "Node") val node: TreeNode? = null
) {}
