/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param driver
 * @param dsn
 */
data class RegistryDao(
    @Json(name = "driver") val driver: kotlin.String? = null,
    @Json(name = "dsn") val dsn: kotlin.String? = null
) {}
