/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param actions
 * @param ids
 * @param metaName
 * @param metaValue
 * @param names
 * @param ttl
 * @param types
 */
data class RegistryOptions(
    @Json(name = "actions") val actions: kotlin.collections.List<RegistryActionType>? = null,
    @Json(name = "ids") val ids: kotlin.collections.List<kotlin.String>? = null,
    @Json(name = "metaName") val metaName: kotlin.String? = null,
    @Json(name = "metaValue") val metaValue: kotlin.String? = null,
    @Json(name = "names") val names: kotlin.collections.List<kotlin.String>? = null,
    @Json(name = "ttl") val ttl: kotlin.String? = null,
    @Json(name = "types") val types: kotlin.collections.List<RegistryItemType>? = null
) {}
