/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param options
 * @param tags
 * @param version
 */
data class RegistryService(
    @Json(name = "options") val options: RegistryOptions? = null,
    @Json(name = "tags") val tags: kotlin.collections.List<kotlin.String>? = null,
    @Json(name = "version") val version: kotlin.String? = null
) {}
