/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.pydio.kotlin.openapi.model

import com.pydio.kotlin.openapi.model.RestShareLink

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param createPassword 
 * @param link 
 * @param passwordEnabled 
 * @param updateCustomHash 
 * @param updatePassword 
 * @param uuid 
 */


data class RestUpsertPublicLinkRequest (

    @Json(name = "CreatePassword")
    val createPassword: kotlin.String? = null,

    @Json(name = "Link")
    val link: RestShareLink? = null,

    @Json(name = "PasswordEnabled")
    val passwordEnabled: kotlin.Boolean? = null,

    @Json(name = "UpdateCustomHash")
    val updateCustomHash: kotlin.String? = null,

    @Json(name = "UpdatePassword")
    val updatePassword: kotlin.String? = null,

    @Json(name = "Uuid")
    val uuid: kotlin.String? = null

) {


}

