/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param total
 * @param workspaces
 */
data class RestWorkspaceCollection(
    @Json(name = "Total") val total: kotlin.Int? = null,
    @Json(name = "Workspaces") val workspaces: kotlin.collections.List<IdmWorkspace>? = null
) {}
