/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param nodes
 * @param pagination
 */
data class RestBulkMetaResponse(
    @Json(name = "Nodes") val nodes: kotlin.collections.List<TreeNode>? = null,
    @Json(name = "Pagination") val pagination: RestPagination? = null
) {}
