/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param children
 * @param parent
 */
data class RestNodesCollection(
    @Json(name = "Children") val children: kotlin.collections.List<TreeNode>? = null,
    @Json(name = "Parent") val parent: TreeNode? = null
) {}
