/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/** @param processes */
data class RestListProcessesResponse(
    @Json(name = "Processes") val processes: kotlin.collections.List<RestProcess>? = null
) {}
