/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.pydio.kotlin.openapi.model

import com.pydio.kotlin.openapi.model.IdmACLAction
import com.pydio.kotlin.openapi.model.IdmRole
import com.pydio.kotlin.openapi.model.IdmUser

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param actions 
 * @param group 
 * @param isUserRole 
 * @param role 
 * @param roleId 
 * @param user 
 */


data class RestCellAcl (

    @Json(name = "Actions")
    val actions: kotlin.collections.List<IdmACLAction>? = null,

    @Json(name = "Group")
    val group: IdmUser? = null,

    @Json(name = "IsUserRole")
    val isUserRole: kotlin.Boolean? = null,

    @Json(name = "Role")
    val role: IdmRole? = null,

    @Json(name = "RoleId")
    val roleId: kotlin.String? = null,

    @Json(name = "User")
    val user: IdmUser? = null

) {


}

