/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param `data`
 * @param fullPath
 */
data class RestConfiguration(
    @Json(name = "Data") val `data`: kotlin.String? = null,
    @Json(name = "FullPath") val fullPath: kotlin.String? = null
) {}
