/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param belongsToTeams
 * @param sharedCells
 */
data class RestRelationResponse(
    @Json(name = "BelongsToTeams") val belongsToTeams: kotlin.collections.List<IdmRole>? = null,
    @Json(name = "SharedCells") val sharedCells: kotlin.collections.List<IdmWorkspace>? = null
) {}
