/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param bucketsRegexp
 * @param dataSource
 */
data class RestListStorageBucketsRequest(
    @Json(name = "BucketsRegexp") val bucketsRegexp: kotlin.String? = null,
    @Json(name = "DataSource") val dataSource: ObjectDataSource? = null
) {}
