/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param sections
 * @param metadata
 */
data class RestSettingsMenuResponse(
    @Json(name = "Sections") val sections: kotlin.collections.List<RestSettingsSection>? = null,
    @Json(name = "__metadata__") val metadata: RestSettingsEntryMeta? = null
) {}
