/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.pydio.kotlin.openapi.model

import com.pydio.kotlin.openapi.model.RestNodeLocator
import com.pydio.kotlin.openapi.model.TreeNodeType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param contentType 
 * @param locator 
 * @param templateUuid 
 * @param type 
 */


data class RestIncomingNode (

    @Json(name = "ContentType")
    val contentType: kotlin.String? = null,

    @Json(name = "Locator")
    val locator: RestNodeLocator? = null,

    @Json(name = "TemplateUuid")
    val templateUuid: kotlin.String? = null,

    @Json(name = "Type")
    val type: TreeNodeType? = TreeNodeType.UNKNOWN

) {


}

