/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.pydio.kotlin.openapi.model

import com.pydio.kotlin.openapi.model.RestNode
import com.pydio.kotlin.openapi.model.RestPagination
import com.pydio.kotlin.openapi.model.TreeSearchFacet

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param facets 
 * @param nodes 
 * @param pagination 
 */


data class RestNodeCollection (

    @Json(name = "Facets")
    val facets: kotlin.collections.List<TreeSearchFacet>? = null,

    @Json(name = "Nodes")
    val nodes: kotlin.collections.List<RestNode>? = null,

    @Json(name = "Pagination")
    val pagination: RestPagination? = null

) {


}

