/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param components
 * @param status
 */
data class RestHealthServiceResponse(
    @Json(name = "Components")
    val components: kotlin.collections.Map<kotlin.String, RestComponentStatus>? = null,
    @Json(name = "Status") val status: kotlin.String? = null
) {}
