/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import com.squareup.moshi.Json

/**
 * @param intervalStart
 * @param maxNumber
 */
data class TreeVersioningKeepPeriod(
    @Json(name = "IntervalStart") val intervalStart: kotlin.String? = null,
    @Json(name = "MaxNumber") val maxNumber: kotlin.Int? = null
) {}
