/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.pydio.kotlin.openapi.model

import com.pydio.kotlin.openapi.model.UpdatePackage

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param availableBinaries 
 * @param channel 
 */


data class UpdateUpdateResponse (

    @Json(name = "AvailableBinaries")
    val availableBinaries: kotlin.collections.List<UpdatePackage>? = null,

    @Json(name = "Channel")
    val channel: kotlin.String? = null

) {


}

