/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.v2.moshi.model

import com.squareup.moshi.Json

/**
 * @param exists
 * @param inputLocator
 * @param nextPath
 * @param node
 */
data class RestCheckResult(
    @Json(name = "Exists") val exists: kotlin.Boolean? = null,
    @Json(name = "InputLocator") val inputLocator: RestNodeLocator? = null,
    @Json(name = "NextPath") val nextPath: kotlin.String? = null,
    @Json(name = "Node") val node: RestNode? = null
) {}
