/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.pydio.kotlin.openapi.v2.moshi.model

import com.pydio.kotlin.openapi.v2.moshi.model.IdmWorkspaceScope

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Current workspace information, maybe published on the root node of a workspace
 *
 * @param slug 
 * @param uuid 
 * @param description 
 * @param isRoot 
 * @param isVirtualRoot 
 * @param label 
 * @param permissions 
 * @param quota 
 * @param quotaUsage 
 * @param scope 
 * @param skipRecycle 
 * @param syncable 
 */


data class RestContextWorkspace (

    @Json(name = "Slug")
    val slug: kotlin.String,

    @Json(name = "Uuid")
    val uuid: kotlin.String,

    @Json(name = "Description")
    val description: kotlin.String? = null,

    @Json(name = "IsRoot")
    val isRoot: kotlin.Boolean? = null,

    @Json(name = "IsVirtualRoot")
    val isVirtualRoot: kotlin.Boolean? = null,

    @Json(name = "Label")
    val label: kotlin.String? = null,

    @Json(name = "Permissions")
    val permissions: kotlin.String? = null,

    @Json(name = "Quota")
    val quota: kotlin.String? = null,

    @Json(name = "QuotaUsage")
    val quotaUsage: kotlin.String? = null,

    @Json(name = "Scope")
    val scope: IdmWorkspaceScope? = IdmWorkspaceScope.ANY,

    @Json(name = "SkipRecycle")
    val skipRecycle: kotlin.Boolean? = null,

    @Json(name = "Syncable")
    val syncable: kotlin.Boolean? = null

) {


}

