/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.pydio.kotlin.openapi.kmp.model

import com.pydio.kotlin.openapi.kmp.model.JobsCommand

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param cmd 
 * @param jobId 
 * @param ownerId 
 * @param runParameters 
 * @param taskId 
 */
@Serializable

data class JobsCtrlCommand (

    @SerialName(value = "Cmd") val cmd: JobsCommand? = JobsCommand.None,

    @SerialName(value = "JobId") val jobId: kotlin.String? = null,

    @SerialName(value = "OwnerId") val ownerId: kotlin.String? = null,

    @SerialName(value = "RunParameters") val runParameters: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "TaskId") val taskId: kotlin.String? = null

) {


}

