/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.pydio.kotlin.openapi.kmp.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param uuid 
 * @param description 
 */
@Serializable

data class RestRevisionMeta (

    @SerialName(value = "Uuid") @Required val uuid: kotlin.String,

    @SerialName(value = "Description") val description: kotlin.String? = null

) {


}

