/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.pydio.kotlin.openapi.kmp.model

import com.pydio.kotlin.openapi.kmp.model.RestShareLink

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param link 
 * @param createPassword 
 * @param passwordEnabled 
 * @param updateCustomHash 
 * @param updatePassword 
 */
@Serializable

data class RestPublicLinkRequest (

    @SerialName(value = "Link") @Required val link: RestShareLink,

    @SerialName(value = "CreatePassword") val createPassword: kotlin.String? = null,

    @SerialName(value = "PasswordEnabled") val passwordEnabled: kotlin.Boolean? = null,

    @SerialName(value = "UpdateCustomHash") val updateCustomHash: kotlin.String? = null,

    @SerialName(value = "UpdatePassword") val updatePassword: kotlin.String? = null

) {


}

