[versions]
# Plugins
#android-gradle-plugin = "8.6.1"
gradle = "8.6.1"
kotlin = "2.0.0"

## SDK OpenAPI
okhttp-version = "4.12.0"
moshi-version = "1.11.0"
logging-interceptor-version = "4.12.0"

junit-version = "4.13.2"
#kotlinx-coroutines-test-version = "1.8.1"

## SDK Kotlin
gson-version = "2.11.0"

[libraries]
## Base libraries
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

#kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

## SDK OpenAPI
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp-version" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor-version" }
# OpenAPI
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi-version" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi-version" }

## SDK Kotlin
gson = { module = "com.google.code.gson:gson", version.ref = "gson-version" }

# Tests
#kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-test-version" }
junit = { module = "junit:junit", version.ref = "junit-version" }

[plugins]
