/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.pydio.kotlin.openapi.kmp.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.pydio.kotlin.openapi.kmp.model.ActivitySubscription
import com.pydio.kotlin.openapi.kmp.model.ActivityOwnerType

class ActivitySubscriptionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActivitySubscription
        //val modelInstance = ActivitySubscription()

        // to test the property `events`
        should("test events") {
            // uncomment below to test the property
            //modelInstance.events shouldBe ("TODO")
        }

        // to test the property `objectId`
        should("test objectId") {
            // uncomment below to test the property
            //modelInstance.objectId shouldBe ("TODO")
        }

        // to test the property `objectType`
        should("test objectType") {
            // uncomment below to test the property
            //modelInstance.objectType shouldBe ("TODO")
        }

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

    }
}
