/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.pydio.kotlin.openapi.kmp.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.pydio.kotlin.openapi.kmp.model.RestUserMetaList
import com.pydio.kotlin.openapi.kmp.model.RestUserMeta

class RestUserMetaListTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RestUserMetaList
        //val modelInstance = RestUserMetaList()

        // to test the property `userMeta`
        should("test userMeta") {
            // uncomment below to test the property
            //modelInstance.userMeta shouldBe ("TODO")
        }

    }
}
