/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.pydio.kotlin.openapi.kmp.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.pydio.kotlin.openapi.kmp.model.ServiceResourcePolicy
import com.pydio.kotlin.openapi.kmp.model.ServiceResourcePolicyAction
import com.pydio.kotlin.openapi.kmp.model.ServiceResourcePolicyPolicyEffect

class ServiceResourcePolicyTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ServiceResourcePolicy
        //val modelInstance = ServiceResourcePolicy()

        // to test the property `action`
        should("test action") {
            // uncomment below to test the property
            //modelInstance.action shouldBe ("TODO")
        }

        // to test the property `effect`
        should("test effect") {
            // uncomment below to test the property
            //modelInstance.effect shouldBe ("TODO")
        }

        // to test the property `jsonConditions`
        should("test jsonConditions") {
            // uncomment below to test the property
            //modelInstance.jsonConditions shouldBe ("TODO")
        }

        // to test the property `resource`
        should("test resource") {
            // uncomment below to test the property
            //modelInstance.resource shouldBe ("TODO")
        }

        // to test the property `subject`
        should("test subject") {
            // uncomment below to test the property
            //modelInstance.subject shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

    }
}
