/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.pydio.kotlin.openapi.kmp.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.pydio.kotlin.openapi.kmp.model.TreeGeoPoint

class TreeGeoPointTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TreeGeoPoint
        //val modelInstance = TreeGeoPoint()

        // to test the property `lat`
        should("test lat") {
            // uncomment below to test the property
            //modelInstance.lat shouldBe ("TODO")
        }

        // to test the property `lon`
        should("test lon") {
            // uncomment below to test the property
            //modelInstance.lon shouldBe ("TODO")
        }

    }
}
