/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.api

import io.kotlintest.specs.ShouldSpec

class AdminTreeServiceApiTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of AdminTreeServiceApi
    // val apiInstance = AdminTreeServiceApi()

    // to test listAdminTree
    should("test listAdminTree") {
      // uncomment below to test listAdminTree
      // val body : TreeListNodesRequest =  // TreeListNodesRequest |
      // val result : RestNodesCollection = apiInstance.listAdminTree(body)
      // result shouldBe ("TODO")
    }

    // to test statAdminTree
    should("test statAdminTree") {
      // uncomment below to test statAdminTree
      // val body : TreeReadNodeRequest =  // TreeReadNodeRequest |
      // val result : TreeReadNodeResponse = apiInstance.statAdminTree(body)
      // result shouldBe ("TODO")
    }
  }
}
