/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.api

import io.kotlintest.specs.ShouldSpec

class GraphServiceApiTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of GraphServiceApi
    // val apiInstance = GraphServiceApi()

    // to test recommend
    should("test recommend") {
      // uncomment below to test recommend
      // val body : RestRecommendRequest =  // RestRecommendRequest |
      // val result : RestRecommendResponse = apiInstance.recommend(body)
      // result shouldBe ("TODO")
    }

    // to test relation
    should("test relation") {
      // uncomment below to test relation
      // val userId : kotlin.String = userId_example // kotlin.String |
      // val result : RestRelationResponse = apiInstance.relation(userId)
      // result shouldBe ("TODO")
    }

    // to test userState
    should("test userState") {
      // uncomment below to test userState
      // val segment : kotlin.String = segment_example // kotlin.String |
      // val result : RestUserStateResponse = apiInstance.userState(segment)
      // result shouldBe ("TODO")
    }
  }
}
