/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.api

import io.kotlintest.specs.ShouldSpec

class HealthServiceApiTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of HealthServiceApi
    // val apiInstance = HealthServiceApi()

    // to test apiLive
    should("test apiLive") {
      // uncomment below to test apiLive
      // val serviceName : kotlin.String = serviceName_example // kotlin.String |
      // val result : RestHealthServiceResponse = apiInstance.apiLive(serviceName)
      // result shouldBe ("TODO")
    }

    // to test apiPing
    should("test apiPing") {
      // uncomment below to test apiPing
      // val serviceName : kotlin.String = serviceName_example // kotlin.String |
      // val result : RestHealthServiceResponse = apiInstance.apiPing(serviceName)
      // result shouldBe ("TODO")
    }

    // to test apiReady
    should("test apiReady") {
      // uncomment below to test apiReady
      // val serviceName : kotlin.String = serviceName_example // kotlin.String |
      // val result : RestHealthServiceResponse = apiInstance.apiReady(serviceName)
      // result shouldBe ("TODO")
    }

    // to test serviceLive
    should("test serviceLive") {
      // uncomment below to test serviceLive
      // val serviceName : kotlin.String = serviceName_example // kotlin.String |
      // val result : RestHealthServiceResponse = apiInstance.serviceLive(serviceName)
      // result shouldBe ("TODO")
    }

    // to test serviceReady
    should("test serviceReady") {
      // uncomment below to test serviceReady
      // val serviceName : kotlin.String = serviceName_example // kotlin.String |
      // val result : RestHealthServiceResponse = apiInstance.serviceReady(serviceName)
      // result shouldBe ("TODO")
    }
  }
}
