/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.api

import io.kotlintest.specs.ShouldSpec

class LogServiceApiTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of LogServiceApi
    // val apiInstance = LogServiceApi()

    // to test syslog
    should("test syslog") {
      // uncomment below to test syslog
      // val body : LogListLogRequest =  // LogListLogRequest | ListLogRequest launches a
      // parameterised query in the log repository and streams the results.
      // val result : RestLogMessageCollection = apiInstance.syslog(body)
      // result shouldBe ("TODO")
    }
  }
}
