/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.api

import io.kotlintest.specs.ShouldSpec

class MetaServiceApiTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of MetaServiceApi
    // val apiInstance = MetaServiceApi()

    // to test deleteMeta
    should("test deleteMeta") {
      // uncomment below to test deleteMeta
      // val nodePath : kotlin.String = nodePath_example // kotlin.String | Path to the requested
      // node
      // val body : RestMetaNamespaceRequest =  // RestMetaNamespaceRequest |
      // val result : TreeNode = apiInstance.deleteMeta(nodePath, body)
      // result shouldBe ("TODO")
    }

    // to test getBulkMeta
    should("test getBulkMeta") {
      // uncomment below to test getBulkMeta
      // val body : RestGetBulkMetaRequest =  // RestGetBulkMetaRequest |
      // val result : RestBulkMetaResponse = apiInstance.getBulkMeta(body)
      // result shouldBe ("TODO")
    }

    // to test getMeta
    should("test getMeta") {
      // uncomment below to test getMeta
      // val nodePath : kotlin.String = nodePath_example // kotlin.String | Path to the requested
      // node
      // val body : RestMetaNamespaceRequest =  // RestMetaNamespaceRequest |
      // val result : TreeNode = apiInstance.getMeta(nodePath, body)
      // result shouldBe ("TODO")
    }

    // to test setMeta
    should("test setMeta") {
      // uncomment below to test setMeta
      // val nodePath : kotlin.String = nodePath_example // kotlin.String |
      // val body : RestMetaCollection =  // RestMetaCollection |
      // val result : TreeNode = apiInstance.setMeta(nodePath, body)
      // result shouldBe ("TODO")
    }
  }
}
