/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.api

import io.kotlintest.specs.ShouldSpec

class SearchServiceApiTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of SearchServiceApi
    // val apiInstance = SearchServiceApi()

    // to test nodes
    should("test nodes") {
      // uncomment below to test nodes
      // val body : TreeSearchRequest =  // TreeSearchRequest |
      // val result : RestSearchResults = apiInstance.nodes(body)
      // result shouldBe ("TODO")
    }
  }
}
