/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.api

import io.kotlintest.specs.ShouldSpec

class ShareServiceApiTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of ShareServiceApi
    // val apiInstance = ShareServiceApi()

    // to test deleteCell
    should("test deleteCell") {
      // uncomment below to test deleteCell
      // val uuid : kotlin.String = uuid_example // kotlin.String | Cell Uuid
      // val result : RestDeleteCellResponse = apiInstance.deleteCell(uuid)
      // result shouldBe ("TODO")
    }

    // to test deleteShareLink
    should("test deleteShareLink") {
      // uncomment below to test deleteShareLink
      // val uuid : kotlin.String = uuid_example // kotlin.String | Id of Link to delete
      // val result : RestDeleteShareLinkResponse = apiInstance.deleteShareLink(uuid)
      // result shouldBe ("TODO")
    }

    // to test getCell
    should("test getCell") {
      // uncomment below to test getCell
      // val uuid : kotlin.String = uuid_example // kotlin.String | Cell Uuid
      // val result : RestCell = apiInstance.getCell(uuid)
      // result shouldBe ("TODO")
    }

    // to test getShareLink
    should("test getShareLink") {
      // uncomment below to test getShareLink
      // val uuid : kotlin.String = uuid_example // kotlin.String | Link Uuid
      // val result : RestShareLink = apiInstance.getShareLink(uuid)
      // result shouldBe ("TODO")
    }

    // to test listSharedResources
    should("test listSharedResources") {
      // uncomment below to test listSharedResources
      // val body : RestListSharedResourcesRequest =  // RestListSharedResourcesRequest |
      // val result : RestListSharedResourcesResponse = apiInstance.listSharedResources(body)
      // result shouldBe ("TODO")
    }

    // to test putCell
    should("test putCell") {
      // uncomment below to test putCell
      // val body : RestPutCellRequest =  // RestPutCellRequest |
      // val result : RestCell = apiInstance.putCell(body)
      // result shouldBe ("TODO")
    }

    // to test putShareLink
    should("test putShareLink") {
      // uncomment below to test putShareLink
      // val body : RestPutShareLinkRequest =  // RestPutShareLinkRequest |
      // val result : RestShareLink = apiInstance.putShareLink(body)
      // result shouldBe ("TODO")
    }

    // to test updateSharePolicies
    should("test updateSharePolicies") {
      // uncomment below to test updateSharePolicies
      // val body : RestUpdateSharePoliciesRequest =  // RestUpdateSharePoliciesRequest |
      // val result : RestUpdateSharePoliciesResponse = apiInstance.updateSharePolicies(body)
      // result shouldBe ("TODO")
    }
  }
}
