/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.api

import io.kotlintest.specs.ShouldSpec

class TemplatesServiceApiTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of TemplatesServiceApi
    // val apiInstance = TemplatesServiceApi()

    // to test listTemplates
    should("test listTemplates") {
      // uncomment below to test listTemplates
      // val templateType : kotlin.String = templateType_example // kotlin.String |
      // val result : RestListTemplatesResponse = apiInstance.listTemplates(templateType)
      // result shouldBe ("TODO")
    }
  }
}
