/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.api

import io.kotlintest.specs.ShouldSpec

class TokenServiceApiTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of TokenServiceApi
    // val apiInstance = TokenServiceApi()

    // to test generateDocumentAccessToken
    should("test generateDocumentAccessToken") {
      // uncomment below to test generateDocumentAccessToken
      // val body : RestDocumentAccessTokenRequest =  // RestDocumentAccessTokenRequest |
      // val result : RestDocumentAccessTokenResponse =
      // apiInstance.generateDocumentAccessToken(body)
      // result shouldBe ("TODO")
    }

    // to test resetPassword
    should("test resetPassword") {
      // uncomment below to test resetPassword
      // val body : RestResetPasswordRequest =  // RestResetPasswordRequest |
      // val result : RestResetPasswordResponse = apiInstance.resetPassword(body)
      // result shouldBe ("TODO")
    }

    // to test resetPasswordToken
    should("test resetPasswordToken") {
      // uncomment below to test resetPasswordToken
      // val userLogin : kotlin.String = userLogin_example // kotlin.String | Start a ResetPassword
      // workflow for this user
      // val body : TokenServiceResetPasswordTokenBody =  // TokenServiceResetPasswordTokenBody |
      // val result : RestResetPasswordTokenResponse = apiInstance.resetPasswordToken(userLogin,
      // body)
      // result shouldBe ("TODO")
    }

    // to test revoke
    should("test revoke") {
      // uncomment below to test revoke
      // val body : RestRevokeRequest =  // RestRevokeRequest |
      // val result : RestRevokeResponse = apiInstance.revoke(body)
      // result shouldBe ("TODO")
    }
  }
}
