/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.api

import io.kotlintest.specs.ShouldSpec

class TreeServiceApiTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of TreeServiceApi
    // val apiInstance = TreeServiceApi()

    // to test bulkStatNodes
    should("test bulkStatNodes") {
      // uncomment below to test bulkStatNodes
      // val body : RestGetBulkMetaRequest =  // RestGetBulkMetaRequest |
      // val result : RestBulkMetaResponse = apiInstance.bulkStatNodes(body)
      // result shouldBe ("TODO")
    }

    // to test createNodes
    should("test createNodes") {
      // uncomment below to test createNodes
      // val body : RestCreateNodesRequest =  // RestCreateNodesRequest |
      // val result : RestNodesCollection = apiInstance.createNodes(body)
      // result shouldBe ("TODO")
    }

    // to test createSelection
    should("test createSelection") {
      // uncomment below to test createSelection
      // val body : RestCreateSelectionRequest =  // RestCreateSelectionRequest |
      // val result : RestCreateSelectionResponse = apiInstance.createSelection(body)
      // result shouldBe ("TODO")
    }

    // to test deleteNodes
    should("test deleteNodes") {
      // uncomment below to test deleteNodes
      // val body : RestDeleteNodesRequest =  // RestDeleteNodesRequest |
      // val result : RestDeleteNodesResponse = apiInstance.deleteNodes(body)
      // result shouldBe ("TODO")
    }

    // to test headNode
    should("test headNode") {
      // uncomment below to test headNode
      // val node : kotlin.String = node_example // kotlin.String | The node to state
      // val result : RestHeadNodeResponse = apiInstance.headNode(node)
      // result shouldBe ("TODO")
    }

    // to test restoreNodes
    should("test restoreNodes") {
      // uncomment below to test restoreNodes
      // val body : RestRestoreNodesRequest =  // RestRestoreNodesRequest |
      // val result : RestRestoreNodesResponse = apiInstance.restoreNodes(body)
      // result shouldBe ("TODO")
    }
  }
}
