/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.api

import io.kotlintest.specs.ShouldSpec

class UpdateServiceApiTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of UpdateServiceApi
    // val apiInstance = UpdateServiceApi()

    // to test applyUpdate
    should("test applyUpdate") {
      // uncomment below to test applyUpdate
      // val targetVersion : kotlin.String = targetVersion_example // kotlin.String | Version of the
      // target binary
      // val body : UpdateApplyUpdateRequest =  // UpdateApplyUpdateRequest |
      // val result : UpdateApplyUpdateResponse = apiInstance.applyUpdate(targetVersion, body)
      // result shouldBe ("TODO")
    }

    // to test updateRequired
    should("test updateRequired") {
      // uncomment below to test updateRequired
      // val body : UpdateUpdateRequest =  // UpdateUpdateRequest |
      // val result : UpdateUpdateResponse = apiInstance.updateRequired(body)
      // result shouldBe ("TODO")
    }
  }
}
