/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.api

import io.kotlintest.specs.ShouldSpec

class WorkspaceServiceApiTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of WorkspaceServiceApi
    // val apiInstance = WorkspaceServiceApi()

    // to test deleteWorkspace
    should("test deleteWorkspace") {
      // uncomment below to test deleteWorkspace
      // val slug : kotlin.String = slug_example // kotlin.String |
      // val result : RestDeleteResponse = apiInstance.deleteWorkspace(slug)
      // result shouldBe ("TODO")
    }

    // to test putWorkspace
    should("test putWorkspace") {
      // uncomment below to test putWorkspace
      // val slug : kotlin.String = slug_example // kotlin.String | Slug is an url-compatible form
      // of the workspace label, or can be freely modified (max length 500)
      // val body : WorkspaceServicePutWorkspaceBody =  // WorkspaceServicePutWorkspaceBody |
      // val result : IdmWorkspace = apiInstance.putWorkspace(slug, body)
      // result shouldBe ("TODO")
    }

    // to test searchWorkspaces
    should("test searchWorkspaces") {
      // uncomment below to test searchWorkspaces
      // val body : RestSearchWorkspaceRequest =  // RestSearchWorkspaceRequest |
      // val result : RestWorkspaceCollection = apiInstance.searchWorkspaces(body)
      // result shouldBe ("TODO")
    }
  }
}
