/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class AuthTokenTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of AuthToken
    // val modelInstance = AuthToken()

    // to test the property `accessToken`
    should("test accessToken") {
      // uncomment below to test the property
      // modelInstance.accessToken shouldBe ("TODO")
    }

    // to test the property `expiresAt`
    should("test expiresAt") {
      // uncomment below to test the property
      // modelInstance.expiresAt shouldBe ("TODO")
    }

    // to test the property `idToken`
    should("test idToken") {
      // uncomment below to test the property
      // modelInstance.idToken shouldBe ("TODO")
    }

    // to test the property `refreshToken`
    should("test refreshToken") {
      // uncomment below to test the property
      // modelInstance.refreshToken shouldBe ("TODO")
    }
  }
}
