/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class CtlPeerTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of CtlPeer
    // val modelInstance = CtlPeer()

    // to test the property `address`
    should("test address") {
      // uncomment below to test the property
      // modelInstance.address shouldBe ("TODO")
    }

    // to test the property `id`
    should("test id") {
      // uncomment below to test the property
      // modelInstance.id shouldBe ("TODO")
    }

    // to test the property `metadata`
    should("test metadata") {
      // uncomment below to test the property
      // modelInstance.metadata shouldBe ("TODO")
    }

    // to test the property `port`
    should("test port") {
      // uncomment below to test the property
      // modelInstance.port shouldBe ("TODO")
    }
  }
}
