/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class CtlServiceTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of CtlService
    // val modelInstance = CtlService()

    // to test the property `controllable`
    should("test controllable") {
      // uncomment below to test the property
      // modelInstance.controllable shouldBe ("TODO")
    }

    // to test the property `description`
    should("test description") {
      // uncomment below to test the property
      // modelInstance.description shouldBe ("TODO")
    }

    // to test the property `metadata`
    should("test metadata") {
      // uncomment below to test the property
      // modelInstance.metadata shouldBe ("TODO")
    }

    // to test the property `name`
    should("test name") {
      // uncomment below to test the property
      // modelInstance.name shouldBe ("TODO")
    }

    // to test the property `runningPeers`
    should("test runningPeers") {
      // uncomment below to test the property
      // modelInstance.runningPeers shouldBe ("TODO")
    }

    // to test the property `status`
    should("test status") {
      // uncomment below to test the property
      // modelInstance.status shouldBe ("TODO")
    }

    // to test the property `tag`
    should("test tag") {
      // uncomment below to test the property
      // modelInstance.tag shouldBe ("TODO")
    }

    // to test the property `version`
    should("test version") {
      // uncomment below to test the property
      // modelInstance.version shouldBe ("TODO")
    }
  }
}
