/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class EncryptionAdminListKeysRequestTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of EncryptionAdminListKeysRequest
    // val modelInstance = EncryptionAdminListKeysRequest()

    // to test the property `all`
    should("test all") {
      // uncomment below to test the property
      // modelInstance.all shouldBe ("TODO")
    }
  }
}
