/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class EncryptionAdminListKeysResponseTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of EncryptionAdminListKeysResponse
    // val modelInstance = EncryptionAdminListKeysResponse()

    // to test the property `propertyKeys`
    should("test propertyKeys") {
      // uncomment below to test the property
      // modelInstance.propertyKeys shouldBe ("TODO")
    }
  }
}
