/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class EncryptionAdminExportKeyRequestTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of EncryptionAdminExportKeyRequest
    // val modelInstance = EncryptionAdminExportKeyRequest()

    // to test the property `keyID`
    should("test keyID") {
      // uncomment below to test the property
      // modelInstance.keyID shouldBe ("TODO")
    }

    // to test the property `strPassword`
    should("test strPassword") {
      // uncomment below to test the property
      // modelInstance.strPassword shouldBe ("TODO")
    }
  }
}
