/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class EncryptionKeyInfoTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of EncryptionKeyInfo
    // val modelInstance = EncryptionKeyInfo()

    // to test the property `exports`
    should("test exports") {
      // uncomment below to test the property
      // modelInstance.exports shouldBe ("TODO")
    }

    // to test the property `imports`
    should("test imports") {
      // uncomment below to test the property
      // modelInstance.imports shouldBe ("TODO")
    }
  }
}
