/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class EncryptionAdminCreateKeyRequestTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of EncryptionAdminCreateKeyRequest
    // val modelInstance = EncryptionAdminCreateKeyRequest()

    // to test the property `keyID`
    should("test keyID") {
      // uncomment below to test the property
      // modelInstance.keyID shouldBe ("TODO")
    }

    // to test the property `label`
    should("test label") {
      // uncomment below to test the property
      // modelInstance.label shouldBe ("TODO")
    }
  }
}
