/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class IdmACLTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of IdmACL
    // val modelInstance = IdmACL()

    // to test the property `action`
    should("test action") {
      // uncomment below to test the property
      // modelInstance.action shouldBe ("TODO")
    }

    // to test the property `ID`
    should("test ID") {
      // uncomment below to test the property
      // modelInstance.ID shouldBe ("TODO")
    }

    // to test the property `nodeID`
    should("test nodeID") {
      // uncomment below to test the property
      // modelInstance.nodeID shouldBe ("TODO")
    }

    // to test the property `roleID`
    should("test roleID") {
      // uncomment below to test the property
      // modelInstance.roleID shouldBe ("TODO")
    }

    // to test the property `workspaceID`
    should("test workspaceID") {
      // uncomment below to test the property
      // modelInstance.workspaceID shouldBe ("TODO")
    }
  }
}
