/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class IdmACLActionTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of IdmACLAction
    // val modelInstance = IdmACLAction()

    // to test the property `name`
    should("test name") {
      // uncomment below to test the property
      // modelInstance.name shouldBe ("TODO")
    }

    // to test the property ``value``
    should("test `value`") {
      // uncomment below to test the property
      // modelInstance.`value` shouldBe ("TODO")
    }
  }
}
