/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class IdmListPolicyGroupsRequestTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of IdmListPolicyGroupsRequest
    // val modelInstance = IdmListPolicyGroupsRequest()

    // to test the property `filter`
    should("test filter") {
      // uncomment below to test the property
      // modelInstance.filter shouldBe ("TODO")
    }
  }
}
