/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class IdmPolicyTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of IdmPolicy
    // val modelInstance = IdmPolicy()

    // to test the property `ormActions`
    should("test ormActions") {
      // uncomment below to test the property
      // modelInstance.ormActions shouldBe ("TODO")
    }

    // to test the property `ormResources`
    should("test ormResources") {
      // uncomment below to test the property
      // modelInstance.ormResources shouldBe ("TODO")
    }

    // to test the property `ormSubjects`
    should("test ormSubjects") {
      // uncomment below to test the property
      // modelInstance.ormSubjects shouldBe ("TODO")
    }

    // to test the property `actions`
    should("test actions") {
      // uncomment below to test the property
      // modelInstance.actions shouldBe ("TODO")
    }

    // to test the property `conditions`
    should("test conditions") {
      // uncomment below to test the property
      // modelInstance.conditions shouldBe ("TODO")
    }

    // to test the property `description`
    should("test description") {
      // uncomment below to test the property
      // modelInstance.description shouldBe ("TODO")
    }

    // to test the property `effect`
    should("test effect") {
      // uncomment below to test the property
      // modelInstance.effect shouldBe ("TODO")
    }

    // to test the property `id`
    should("test id") {
      // uncomment below to test the property
      // modelInstance.id shouldBe ("TODO")
    }

    // to test the property `resources`
    should("test resources") {
      // uncomment below to test the property
      // modelInstance.resources shouldBe ("TODO")
    }

    // to test the property `subjects`
    should("test subjects") {
      // uncomment below to test the property
      // modelInstance.subjects shouldBe ("TODO")
    }
  }
}
