/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class IdmPolicySubjectTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of IdmPolicySubject
    // val modelInstance = IdmPolicySubject()

    // to test the property `compiled`
    should("test compiled") {
      // uncomment below to test the property
      // modelInstance.compiled shouldBe ("TODO")
    }

    // to test the property `hasRegex`
    should("test hasRegex") {
      // uncomment below to test the property
      // modelInstance.hasRegex shouldBe ("TODO")
    }

    // to test the property `ID`
    should("test ID") {
      // uncomment below to test the property
      // modelInstance.ID shouldBe ("TODO")
    }

    // to test the property `template`
    should("test template") {
      // uncomment below to test the property
      // modelInstance.template shouldBe ("TODO")
    }
  }
}
