/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class IdmPolicyConditionTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of IdmPolicyCondition
    // val modelInstance = IdmPolicyCondition()

    // to test the property `jsonOptions`
    should("test jsonOptions") {
      // uncomment below to test the property
      // modelInstance.jsonOptions shouldBe ("TODO")
    }

    // to test the property `type`
    should("test type") {
      // uncomment below to test the property
      // modelInstance.type shouldBe ("TODO")
    }
  }
}
