/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class IdmRoleTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of IdmRole
    // val modelInstance = IdmRole()

    // to test the property `autoApplies`
    should("test autoApplies") {
      // uncomment below to test the property
      // modelInstance.autoApplies shouldBe ("TODO")
    }

    // to test the property `forceOverride` - Is used in a stack of roles, this one will always be
    // applied last.
    should("test forceOverride") {
      // uncomment below to test the property
      // modelInstance.forceOverride shouldBe ("TODO")
    }

    // to test the property `groupRole`
    should("test groupRole") {
      // uncomment below to test the property
      // modelInstance.groupRole shouldBe ("TODO")
    }

    // to test the property `isTeam`
    should("test isTeam") {
      // uncomment below to test the property
      // modelInstance.isTeam shouldBe ("TODO")
    }

    // to test the property `label`
    should("test label") {
      // uncomment below to test the property
      // modelInstance.label shouldBe ("TODO")
    }

    // to test the property `lastUpdated`
    should("test lastUpdated") {
      // uncomment below to test the property
      // modelInstance.lastUpdated shouldBe ("TODO")
    }

    // to test the property `policies`
    should("test policies") {
      // uncomment below to test the property
      // modelInstance.policies shouldBe ("TODO")
    }

    // to test the property `policiesContextEditable`
    should("test policiesContextEditable") {
      // uncomment below to test the property
      // modelInstance.policiesContextEditable shouldBe ("TODO")
    }

    // to test the property `userRole`
    should("test userRole") {
      // uncomment below to test the property
      // modelInstance.userRole shouldBe ("TODO")
    }

    // to test the property `uuid`
    should("test uuid") {
      // uncomment below to test the property
      // modelInstance.uuid shouldBe ("TODO")
    }
  }
}
