/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class IdmRoleSingleQueryTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of IdmRoleSingleQuery
    // val modelInstance = IdmRoleSingleQuery()

    // to test the property `hasAutoApply`
    should("test hasAutoApply") {
      // uncomment below to test the property
      // modelInstance.hasAutoApply shouldBe ("TODO")
    }

    // to test the property `isGroupRole`
    should("test isGroupRole") {
      // uncomment below to test the property
      // modelInstance.isGroupRole shouldBe ("TODO")
    }

    // to test the property `isTeam`
    should("test isTeam") {
      // uncomment below to test the property
      // modelInstance.isTeam shouldBe ("TODO")
    }

    // to test the property `isUserRole`
    should("test isUserRole") {
      // uncomment below to test the property
      // modelInstance.isUserRole shouldBe ("TODO")
    }

    // to test the property `label`
    should("test label") {
      // uncomment below to test the property
      // modelInstance.label shouldBe ("TODO")
    }

    // to test the property `uuid`
    should("test uuid") {
      // uncomment below to test the property
      // modelInstance.uuid shouldBe ("TODO")
    }

    // to test the property `not`
    should("test not") {
      // uncomment below to test the property
      // modelInstance.not shouldBe ("TODO")
    }
  }
}
