/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class InstallTLSLetsEncryptTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of InstallTLSLetsEncrypt
    // val modelInstance = InstallTLSLetsEncrypt()

    // to test the property `acceptEULA`
    should("test acceptEULA") {
      // uncomment below to test the property
      // modelInstance.acceptEULA shouldBe ("TODO")
    }

    // to test the property `email`
    should("test email") {
      // uncomment below to test the property
      // modelInstance.email shouldBe ("TODO")
    }

    // to test the property `stagingCA`
    should("test stagingCA") {
      // uncomment below to test the property
      // modelInstance.stagingCA shouldBe ("TODO")
    }
  }
}
