/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class InstallTLSSelfSignedTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of InstallTLSSelfSigned
    // val modelInstance = InstallTLSSelfSigned()

    // to test the property `hostnames`
    should("test hostnames") {
      // uncomment below to test the property
      // modelInstance.hostnames shouldBe ("TODO")
    }
  }
}
