/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class JobsListJobsRequestTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of JobsListJobsRequest
    // val modelInstance = JobsListJobsRequest()

    // to test the property `eventsOnly`
    should("test eventsOnly") {
      // uncomment below to test the property
      // modelInstance.eventsOnly shouldBe ("TODO")
    }

    // to test the property `jobIDs`
    should("test jobIDs") {
      // uncomment below to test the property
      // modelInstance.jobIDs shouldBe ("TODO")
    }

    // to test the property `loadTasks`
    should("test loadTasks") {
      // uncomment below to test the property
      // modelInstance.loadTasks shouldBe ("TODO")
    }

    // to test the property `owner`
    should("test owner") {
      // uncomment below to test the property
      // modelInstance.owner shouldBe ("TODO")
    }

    // to test the property `tasksLimit`
    should("test tasksLimit") {
      // uncomment below to test the property
      // modelInstance.tasksLimit shouldBe ("TODO")
    }

    // to test the property `tasksOffset`
    should("test tasksOffset") {
      // uncomment below to test the property
      // modelInstance.tasksOffset shouldBe ("TODO")
    }

    // to test the property `timersOnly`
    should("test timersOnly") {
      // uncomment below to test the property
      // modelInstance.timersOnly shouldBe ("TODO")
    }
  }
}
