/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class JobsScheduleTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of JobsSchedule
    // val modelInstance = JobsSchedule()

    // to test the property `iso8601MinDelta`
    should("test iso8601MinDelta") {
      // uncomment below to test the property
      // modelInstance.iso8601MinDelta shouldBe ("TODO")
    }

    // to test the property `iso8601Schedule` - ISO 8601 Description of the scheduling for instance
    // \"R2/2015-06-04T19:25:16.828696-07:00/PT4S\" where first part is the number of repetitions
    // (if 0, infinite repetition),  second part the starting date and last part, the duration
    // between 2 occurrences.
    should("test iso8601Schedule") {
      // uncomment below to test the property
      // modelInstance.iso8601Schedule shouldBe ("TODO")
    }
  }
}
