/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class JobsTaskTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of JobsTask
    // val modelInstance = JobsTask()

    // to test the property `actionsLogs`
    should("test actionsLogs") {
      // uncomment below to test the property
      // modelInstance.actionsLogs shouldBe ("TODO")
    }

    // to test the property `canPause`
    should("test canPause") {
      // uncomment below to test the property
      // modelInstance.canPause shouldBe ("TODO")
    }

    // to test the property `canStop`
    should("test canStop") {
      // uncomment below to test the property
      // modelInstance.canStop shouldBe ("TODO")
    }

    // to test the property `endTime`
    should("test endTime") {
      // uncomment below to test the property
      // modelInstance.endTime shouldBe ("TODO")
    }

    // to test the property `hasProgress`
    should("test hasProgress") {
      // uncomment below to test the property
      // modelInstance.hasProgress shouldBe ("TODO")
    }

    // to test the property `ID`
    should("test ID") {
      // uncomment below to test the property
      // modelInstance.ID shouldBe ("TODO")
    }

    // to test the property `jobID`
    should("test jobID") {
      // uncomment below to test the property
      // modelInstance.jobID shouldBe ("TODO")
    }

    // to test the property `progress`
    should("test progress") {
      // uncomment below to test the property
      // modelInstance.progress shouldBe ("TODO")
    }

    // to test the property `startTime`
    should("test startTime") {
      // uncomment below to test the property
      // modelInstance.startTime shouldBe ("TODO")
    }

    // to test the property `status`
    should("test status") {
      // uncomment below to test the property
      // modelInstance.status shouldBe ("TODO")
    }

    // to test the property `statusMessage`
    should("test statusMessage") {
      // uncomment below to test the property
      // modelInstance.statusMessage shouldBe ("TODO")
    }

    // to test the property `triggerOwner`
    should("test triggerOwner") {
      // uncomment below to test the property
      // modelInstance.triggerOwner shouldBe ("TODO")
    }
  }
}
