/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class JobsJobParameterTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of JobsJobParameter
    // val modelInstance = JobsJobParameter()

    // to test the property `description`
    should("test description") {
      // uncomment below to test the property
      // modelInstance.description shouldBe ("TODO")
    }

    // to test the property `jsonChoices`
    should("test jsonChoices") {
      // uncomment below to test the property
      // modelInstance.jsonChoices shouldBe ("TODO")
    }

    // to test the property `mandatory`
    should("test mandatory") {
      // uncomment below to test the property
      // modelInstance.mandatory shouldBe ("TODO")
    }

    // to test the property `name`
    should("test name") {
      // uncomment below to test the property
      // modelInstance.name shouldBe ("TODO")
    }

    // to test the property `type`
    should("test type") {
      // uncomment below to test the property
      // modelInstance.type shouldBe ("TODO")
    }

    // to test the property ``value``
    should("test `value`") {
      // uncomment below to test the property
      // modelInstance.`value` shouldBe ("TODO")
    }
  }
}
