/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class JobsActionMessageTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of JobsActionMessage
    // val modelInstance = JobsActionMessage()

    // to test the property `acls`
    should("test acls") {
      // uncomment below to test the property
      // modelInstance.acls shouldBe ("TODO")
    }

    // to test the property `activities`
    should("test activities") {
      // uncomment below to test the property
      // modelInstance.activities shouldBe ("TODO")
    }

    // to test the property `dataSources`
    should("test dataSources") {
      // uncomment below to test the property
      // modelInstance.dataSources shouldBe ("TODO")
    }

    // to test the property `event`
    should("test event") {
      // uncomment below to test the property
      // modelInstance.event shouldBe ("TODO")
    }

    // to test the property `nodes`
    should("test nodes") {
      // uncomment below to test the property
      // modelInstance.nodes shouldBe ("TODO")
    }

    // to test the property `outputChain`
    should("test outputChain") {
      // uncomment below to test the property
      // modelInstance.outputChain shouldBe ("TODO")
    }

    // to test the property `roles`
    should("test roles") {
      // uncomment below to test the property
      // modelInstance.roles shouldBe ("TODO")
    }

    // to test the property `users`
    should("test users") {
      // uncomment below to test the property
      // modelInstance.users shouldBe ("TODO")
    }

    // to test the property `workspaces`
    should("test workspaces") {
      // uncomment below to test the property
      // modelInstance.workspaces shouldBe ("TODO")
    }
  }
}
