/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class JobsDataSelectorTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of JobsDataSelector
    // val modelInstance = JobsDataSelector()

    // to test the property `clearInput`
    should("test clearInput") {
      // uncomment below to test the property
      // modelInstance.clearInput shouldBe ("TODO")
    }

    // to test the property `collect`
    should("test collect") {
      // uncomment below to test the property
      // modelInstance.collect shouldBe ("TODO")
    }

    // to test the property `description`
    should("test description") {
      // uncomment below to test the property
      // modelInstance.description shouldBe ("TODO")
    }

    // to test the property `fanOutInput`
    should("test fanOutInput") {
      // uncomment below to test the property
      // modelInstance.fanOutInput shouldBe ("TODO")
    }

    // to test the property `label`
    should("test label") {
      // uncomment below to test the property
      // modelInstance.label shouldBe ("TODO")
    }

    // to test the property `query`
    should("test query") {
      // uncomment below to test the property
      // modelInstance.query shouldBe ("TODO")
    }

    // to test the property `timeout`
    should("test timeout") {
      // uncomment below to test the property
      // modelInstance.timeout shouldBe ("TODO")
    }
  }
}
