/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class JobsActionOutputTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of JobsActionOutput
    // val modelInstance = JobsActionOutput()

    // to test the property `errorString`
    should("test errorString") {
      // uncomment below to test the property
      // modelInstance.errorString shouldBe ("TODO")
    }

    // to test the property `ignored`
    should("test ignored") {
      // uncomment below to test the property
      // modelInstance.ignored shouldBe ("TODO")
    }

    // to test the property `jsonBody`
    should("test jsonBody") {
      // uncomment below to test the property
      // modelInstance.jsonBody shouldBe ("TODO")
    }

    // to test the property `rawBody`
    should("test rawBody") {
      // uncomment below to test the property
      // modelInstance.rawBody shouldBe ("TODO")
    }

    // to test the property `stringBody`
    should("test stringBody") {
      // uncomment below to test the property
      // modelInstance.stringBody shouldBe ("TODO")
    }

    // to test the property `success`
    should("test success") {
      // uncomment below to test the property
      // modelInstance.success shouldBe ("TODO")
    }

    // to test the property `time`
    should("test time") {
      // uncomment below to test the property
      // modelInstance.time shouldBe ("TODO")
    }

    // to test the property `vars` - Vars container, values are json-encoded.
    should("test vars") {
      // uncomment below to test the property
      // modelInstance.vars shouldBe ("TODO")
    }
  }
}
