/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class JobsDeleteTasksRequestTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of JobsDeleteTasksRequest
    // val modelInstance = JobsDeleteTasksRequest()

    // to test the property `jobId`
    should("test jobId") {
      // uncomment below to test the property
      // modelInstance.jobId shouldBe ("TODO")
    }

    // to test the property `pruneLimit`
    should("test pruneLimit") {
      // uncomment below to test the property
      // modelInstance.pruneLimit shouldBe ("TODO")
    }

    // to test the property `status`
    should("test status") {
      // uncomment below to test the property
      // modelInstance.status shouldBe ("TODO")
    }

    // to test the property `taskID`
    should("test taskID") {
      // uncomment below to test the property
      // modelInstance.taskID shouldBe ("TODO")
    }
  }
}
