/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class LogListLogRequestTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of LogListLogRequest
    // val modelInstance = LogListLogRequest()

    // to test the property `format`
    should("test format") {
      // uncomment below to test the property
      // modelInstance.format shouldBe ("TODO")
    }

    // to test the property `page`
    should("test page") {
      // uncomment below to test the property
      // modelInstance.page shouldBe ("TODO")
    }

    // to test the property `query`
    should("test query") {
      // uncomment below to test the property
      // modelInstance.query shouldBe ("TODO")
    }

    // to test the property `propertySize`
    should("test propertySize") {
      // uncomment below to test the property
      // modelInstance.propertySize shouldBe ("TODO")
    }
  }
}
