/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RegistryServerTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RegistryServer
    // val modelInstance = RegistryServer()

    // to test the property `protocol`
    should("test protocol") {
      // uncomment below to test the property
      // modelInstance.protocol shouldBe ("TODO")
    }
  }
}
