/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RegistryOptionsTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RegistryOptions
    // val modelInstance = RegistryOptions()

    // to test the property `actions`
    should("test actions") {
      // uncomment below to test the property
      // modelInstance.actions shouldBe ("TODO")
    }

    // to test the property `ids`
    should("test ids") {
      // uncomment below to test the property
      // modelInstance.ids shouldBe ("TODO")
    }

    // to test the property `metaName`
    should("test metaName") {
      // uncomment below to test the property
      // modelInstance.metaName shouldBe ("TODO")
    }

    // to test the property `metaValue`
    should("test metaValue") {
      // uncomment below to test the property
      // modelInstance.metaValue shouldBe ("TODO")
    }

    // to test the property `names`
    should("test names") {
      // uncomment below to test the property
      // modelInstance.names shouldBe ("TODO")
    }

    // to test the property `ttl`
    should("test ttl") {
      // uncomment below to test the property
      // modelInstance.ttl shouldBe ("TODO")
    }

    // to test the property `types`
    should("test types") {
      // uncomment below to test the property
      // modelInstance.types shouldBe ("TODO")
    }
  }
}
