/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RegistryServiceTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RegistryService
    // val modelInstance = RegistryService()

    // to test the property `options`
    should("test options") {
      // uncomment below to test the property
      // modelInstance.options shouldBe ("TODO")
    }

    // to test the property `tags`
    should("test tags") {
      // uncomment below to test the property
      // modelInstance.tags shouldBe ("TODO")
    }

    // to test the property `version`
    should("test version") {
      // uncomment below to test the property
      // modelInstance.version shouldBe ("TODO")
    }
  }
}
