/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestUserJobRequestTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestUserJobRequest
    // val modelInstance = RestUserJobRequest()

    // to test the property `jsonParameters`
    should("test jsonParameters") {
      // uncomment below to test the property
      // modelInstance.jsonParameters shouldBe ("TODO")
    }
  }
}
