/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestCellTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestCell
    // val modelInstance = RestCell()

    // to test the property `acLs`
    should("test acLs") {
      // uncomment below to test the property
      // modelInstance.acLs shouldBe ("TODO")
    }

    // to test the property `accessEnd`
    should("test accessEnd") {
      // uncomment below to test the property
      // modelInstance.accessEnd shouldBe ("TODO")
    }

    // to test the property `description`
    should("test description") {
      // uncomment below to test the property
      // modelInstance.description shouldBe ("TODO")
    }

    // to test the property `label`
    should("test label") {
      // uncomment below to test the property
      // modelInstance.label shouldBe ("TODO")
    }

    // to test the property `policies`
    should("test policies") {
      // uncomment below to test the property
      // modelInstance.policies shouldBe ("TODO")
    }

    // to test the property `policiesContextEditable`
    should("test policiesContextEditable") {
      // uncomment below to test the property
      // modelInstance.policiesContextEditable shouldBe ("TODO")
    }

    // to test the property `rootNodes`
    should("test rootNodes") {
      // uncomment below to test the property
      // modelInstance.rootNodes shouldBe ("TODO")
    }

    // to test the property `uuid`
    should("test uuid") {
      // uncomment below to test the property
      // modelInstance.uuid shouldBe ("TODO")
    }
  }
}
