/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestListSharedResourcesResponseTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestListSharedResourcesResponse
    // val modelInstance = RestListSharedResourcesResponse()

    // to test the property `limit`
    should("test limit") {
      // uncomment below to test the property
      // modelInstance.limit shouldBe ("TODO")
    }

    // to test the property `offset`
    should("test offset") {
      // uncomment below to test the property
      // modelInstance.offset shouldBe ("TODO")
    }

    // to test the property `resources`
    should("test resources") {
      // uncomment below to test the property
      // modelInstance.resources shouldBe ("TODO")
    }

    // to test the property `total`
    should("test total") {
      // uncomment below to test the property
      // modelInstance.total shouldBe ("TODO")
    }
  }
}
