/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestResetPasswordRequestTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestResetPasswordRequest
    // val modelInstance = RestResetPasswordRequest()

    // to test the property `newPassword`
    should("test newPassword") {
      // uncomment below to test the property
      // modelInstance.newPassword shouldBe ("TODO")
    }

    // to test the property `resetPasswordToken`
    should("test resetPasswordToken") {
      // uncomment below to test the property
      // modelInstance.resetPasswordToken shouldBe ("TODO")
    }

    // to test the property `userLogin`
    should("test userLogin") {
      // uncomment below to test the property
      // modelInstance.userLogin shouldBe ("TODO")
    }
  }
}
