/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestHeadNodeResponseTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestHeadNodeResponse
    // val modelInstance = RestHeadNodeResponse()

    // to test the property `node`
    should("test node") {
      // uncomment below to test the property
      // modelInstance.node shouldBe ("TODO")
    }
  }
}
