/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestCreatePeerFolderRequestTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestCreatePeerFolderRequest
    // val modelInstance = RestCreatePeerFolderRequest()

    // to test the property `path`
    should("test path") {
      // uncomment below to test the property
      // modelInstance.path shouldBe ("TODO")
    }
  }
}
