/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestSubscriptionsCollectionTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestSubscriptionsCollection
    // val modelInstance = RestSubscriptionsCollection()

    // to test the property `subscriptions`
    should("test subscriptions") {
      // uncomment below to test the property
      // modelInstance.subscriptions shouldBe ("TODO")
    }
  }
}
