/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestMetaCollectionTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestMetaCollection
    // val modelInstance = RestMetaCollection()

    // to test the property `metadatas`
    should("test metadatas") {
      // uncomment below to test the property
      // modelInstance.metadatas shouldBe ("TODO")
    }
  }
}
