/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestListSharedResourcesRequestTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestListSharedResourcesRequest
    // val modelInstance = RestListSharedResourcesRequest()

    // to test the property `limit`
    should("test limit") {
      // uncomment below to test the property
      // modelInstance.limit shouldBe ("TODO")
    }

    // to test the property `offset`
    should("test offset") {
      // uncomment below to test the property
      // modelInstance.offset shouldBe ("TODO")
    }

    // to test the property `ownedBySubject`
    should("test ownedBySubject") {
      // uncomment below to test the property
      // modelInstance.ownedBySubject shouldBe ("TODO")
    }

    // to test the property `shareType`
    should("test shareType") {
      // uncomment below to test the property
      // modelInstance.shareType shouldBe ("TODO")
    }

    // to test the property `subject`
    should("test subject") {
      // uncomment below to test the property
      // modelInstance.subject shouldBe ("TODO")
    }
  }
}
