/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestFrontStateResponseTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestFrontStateResponse
    // val modelInstance = RestFrontStateResponse()

    // to test the property ``data``
    should("test `data`") {
      // uncomment below to test the property
      // modelInstance.`data` shouldBe ("TODO")
    }
  }
}
