/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestFrontSessionResponseTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestFrontSessionResponse
    // val modelInstance = RestFrontSessionResponse()

    // to test the property `error`
    should("test error") {
      // uncomment below to test the property
      // modelInstance.error shouldBe ("TODO")
    }

    // to test the property `expireTime`
    should("test expireTime") {
      // uncomment below to test the property
      // modelInstance.expireTime shouldBe ("TODO")
    }

    // to test the property `JWT`
    should("test JWT") {
      // uncomment below to test the property
      // modelInstance.JWT shouldBe ("TODO")
    }

    // to test the property `redirectTo`
    should("test redirectTo") {
      // uncomment below to test the property
      // modelInstance.redirectTo shouldBe ("TODO")
    }

    // to test the property `token`
    should("test token") {
      // uncomment below to test the property
      // modelInstance.token shouldBe ("TODO")
    }

    // to test the property `trigger`
    should("test trigger") {
      // uncomment below to test the property
      // modelInstance.trigger shouldBe ("TODO")
    }

    // to test the property `triggerInfo`
    should("test triggerInfo") {
      // uncomment below to test the property
      // modelInstance.triggerInfo shouldBe ("TODO")
    }
  }
}
