/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestCreateSelectionResponseTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestCreateSelectionResponse
    // val modelInstance = RestCreateSelectionResponse()

    // to test the property `nodes`
    should("test nodes") {
      // uncomment below to test the property
      // modelInstance.nodes shouldBe ("TODO")
    }

    // to test the property `selectionUUID`
    should("test selectionUUID") {
      // uncomment below to test the property
      // modelInstance.selectionUUID shouldBe ("TODO")
    }
  }
}
