/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestProcessTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestProcess
    // val modelInstance = RestProcess()

    // to test the property `ID`
    should("test ID") {
      // uncomment below to test the property
      // modelInstance.ID shouldBe ("TODO")
    }

    // to test the property `metricsPort`
    should("test metricsPort") {
      // uncomment below to test the property
      // modelInstance.metricsPort shouldBe ("TODO")
    }

    // to test the property `parentID`
    should("test parentID") {
      // uncomment below to test the property
      // modelInstance.parentID shouldBe ("TODO")
    }

    // to test the property `peerAddress`
    should("test peerAddress") {
      // uncomment below to test the property
      // modelInstance.peerAddress shouldBe ("TODO")
    }

    // to test the property `peerId`
    should("test peerId") {
      // uncomment below to test the property
      // modelInstance.peerId shouldBe ("TODO")
    }

    // to test the property `services`
    should("test services") {
      // uncomment below to test the property
      // modelInstance.services shouldBe ("TODO")
    }

    // to test the property `startTag`
    should("test startTag") {
      // uncomment below to test the property
      // modelInstance.startTag shouldBe ("TODO")
    }
  }
}
