/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestActionDescriptionTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestActionDescription
    // val modelInstance = RestActionDescription()

    // to test the property `category`
    should("test category") {
      // uncomment below to test the property
      // modelInstance.category shouldBe ("TODO")
    }

    // to test the property `description`
    should("test description") {
      // uncomment below to test the property
      // modelInstance.description shouldBe ("TODO")
    }

    // to test the property `formModule`
    should("test formModule") {
      // uncomment below to test the property
      // modelInstance.formModule shouldBe ("TODO")
    }

    // to test the property `formModuleProps`
    should("test formModuleProps") {
      // uncomment below to test the property
      // modelInstance.formModuleProps shouldBe ("TODO")
    }

    // to test the property `hasForm`
    should("test hasForm") {
      // uncomment below to test the property
      // modelInstance.hasForm shouldBe ("TODO")
    }

    // to test the property `icon`
    should("test icon") {
      // uncomment below to test the property
      // modelInstance.icon shouldBe ("TODO")
    }

    // to test the property `inputDescription`
    should("test inputDescription") {
      // uncomment below to test the property
      // modelInstance.inputDescription shouldBe ("TODO")
    }

    // to test the property `isInternal` - If action is declared internal, it is hidden to avoid
    // polluting the list.
    should("test isInternal") {
      // uncomment below to test the property
      // modelInstance.isInternal shouldBe ("TODO")
    }

    // to test the property `label`
    should("test label") {
      // uncomment below to test the property
      // modelInstance.label shouldBe ("TODO")
    }

    // to test the property `name`
    should("test name") {
      // uncomment below to test the property
      // modelInstance.name shouldBe ("TODO")
    }

    // to test the property `outputDescription`
    should("test outputDescription") {
      // uncomment below to test the property
      // modelInstance.outputDescription shouldBe ("TODO")
    }

    // to test the property `summaryTemplate`
    should("test summaryTemplate") {
      // uncomment below to test the property
      // modelInstance.summaryTemplate shouldBe ("TODO")
    }

    // to test the property `tint`
    should("test tint") {
      // uncomment below to test the property
      // modelInstance.tint shouldBe ("TODO")
    }
  }
}
