/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestControlServiceRequestTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestControlServiceRequest
    // val modelInstance = RestControlServiceRequest()

    // to test the property `command`
    should("test command") {
      // uncomment below to test the property
      // modelInstance.command shouldBe ("TODO")
    }

    // to test the property `nodeName`
    should("test nodeName") {
      // uncomment below to test the property
      // modelInstance.nodeName shouldBe ("TODO")
    }

    // to test the property `serviceName`
    should("test serviceName") {
      // uncomment below to test the property
      // modelInstance.serviceName shouldBe ("TODO")
    }
  }
}
