/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestSettingsAccessRestPolicyTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestSettingsAccessRestPolicy
    // val modelInstance = RestSettingsAccessRestPolicy()

    // to test the property `action`
    should("test action") {
      // uncomment below to test the property
      // modelInstance.action shouldBe ("TODO")
    }

    // to test the property `resource`
    should("test resource") {
      // uncomment below to test the property
      // modelInstance.resource shouldBe ("TODO")
    }
  }
}
