/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestSearchResultsTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestSearchResults
    // val modelInstance = RestSearchResults()

    // to test the property `facets`
    should("test facets") {
      // uncomment below to test the property
      // modelInstance.facets shouldBe ("TODO")
    }

    // to test the property `results`
    should("test results") {
      // uncomment below to test the property
      // modelInstance.results shouldBe ("TODO")
    }

    // to test the property `total`
    should("test total") {
      // uncomment below to test the property
      // modelInstance.total shouldBe ("TODO")
    }
  }
}
