/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestUserJobResponseTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestUserJobResponse
    // val modelInstance = RestUserJobResponse()

    // to test the property `jobUuid`
    should("test jobUuid") {
      // uncomment below to test the property
      // modelInstance.jobUuid shouldBe ("TODO")
    }
  }
}
