/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestSearchACLRequestTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestSearchACLRequest
    // val modelInstance = RestSearchACLRequest()

    // to test the property `countOnly`
    should("test countOnly") {
      // uncomment below to test the property
      // modelInstance.countOnly shouldBe ("TODO")
    }

    // to test the property `groupBy`
    should("test groupBy") {
      // uncomment below to test the property
      // modelInstance.groupBy shouldBe ("TODO")
    }

    // to test the property `limit`
    should("test limit") {
      // uncomment below to test the property
      // modelInstance.limit shouldBe ("TODO")
    }

    // to test the property `offset`
    should("test offset") {
      // uncomment below to test the property
      // modelInstance.offset shouldBe ("TODO")
    }

    // to test the property `operation`
    should("test operation") {
      // uncomment below to test the property
      // modelInstance.operation shouldBe ("TODO")
    }

    // to test the property `queries`
    should("test queries") {
      // uncomment below to test the property
      // modelInstance.queries shouldBe ("TODO")
    }
  }
}
