/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestUsersCollectionTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestUsersCollection
    // val modelInstance = RestUsersCollection()

    // to test the property `groups`
    should("test groups") {
      // uncomment below to test the property
      // modelInstance.groups shouldBe ("TODO")
    }

    // to test the property `total`
    should("test total") {
      // uncomment below to test the property
      // modelInstance.total shouldBe ("TODO")
    }

    // to test the property `users`
    should("test users") {
      // uncomment below to test the property
      // modelInstance.users shouldBe ("TODO")
    }
  }
}
