/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestFrontEnrollAuthRequestTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestFrontEnrollAuthRequest
    // val modelInstance = RestFrontEnrollAuthRequest()

    // to test the property `enrollInfo`
    should("test enrollInfo") {
      // uncomment below to test the property
      // modelInstance.enrollInfo shouldBe ("TODO")
    }

    // to test the property `enrollType`
    should("test enrollType") {
      // uncomment below to test the property
      // modelInstance.enrollType shouldBe ("TODO")
    }
  }
}
