/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestListProcessesResponseTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestListProcessesResponse
    // val modelInstance = RestListProcessesResponse()

    // to test the property `processes`
    should("test processes") {
      // uncomment below to test the property
      // modelInstance.processes shouldBe ("TODO")
    }
  }
}
