/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestFrontSessionRequestTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestFrontSessionRequest
    // val modelInstance = RestFrontSessionRequest()

    // to test the property `authInfo`
    should("test authInfo") {
      // uncomment below to test the property
      // modelInstance.authInfo shouldBe ("TODO")
    }

    // to test the property `clientTime`
    should("test clientTime") {
      // uncomment below to test the property
      // modelInstance.clientTime shouldBe ("TODO")
    }

    // to test the property `logout`
    should("test logout") {
      // uncomment below to test the property
      // modelInstance.logout shouldBe ("TODO")
    }
  }
}
