/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestMetaNamespaceRequestTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestMetaNamespaceRequest
    // val modelInstance = RestMetaNamespaceRequest()

    // to test the property `namespace`
    should("test namespace") {
      // uncomment below to test the property
      // modelInstance.namespace shouldBe ("TODO")
    }
  }
}
