/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestRecommendRequestTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestRecommendRequest
    // val modelInstance = RestRecommendRequest()

    // to test the property `category`
    should("test category") {
      // uncomment below to test the property
      // modelInstance.category shouldBe ("TODO")
    }

    // to test the property `limit`
    should("test limit") {
      // uncomment below to test the property
      // modelInstance.limit shouldBe ("TODO")
    }

    // to test the property `neighbor`
    should("test neighbor") {
      // uncomment below to test the property
      // modelInstance.neighbor shouldBe ("TODO")
    }

    // to test the property `segment`
    should("test segment") {
      // uncomment below to test the property
      // modelInstance.segment shouldBe ("TODO")
    }
  }
}
