/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestShareLinkTargetUserTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestShareLinkTargetUser
    // val modelInstance = RestShareLinkTargetUser()

    // to test the property `display`
    should("test display") {
      // uncomment below to test the property
      // modelInstance.display shouldBe ("TODO")
    }

    // to test the property `downloadCount`
    should("test downloadCount") {
      // uncomment below to test the property
      // modelInstance.downloadCount shouldBe ("TODO")
    }
  }
}
