/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestRecommendResponseTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestRecommendResponse
    // val modelInstance = RestRecommendResponse()

    // to test the property `nodes`
    should("test nodes") {
      // uncomment below to test the property
      // modelInstance.nodes shouldBe ("TODO")
    }
  }
}
