/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestRolesCollectionTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestRolesCollection
    // val modelInstance = RestRolesCollection()

    // to test the property `roles`
    should("test roles") {
      // uncomment below to test the property
      // modelInstance.roles shouldBe ("TODO")
    }

    // to test the property `total`
    should("test total") {
      // uncomment below to test the property
      // modelInstance.total shouldBe ("TODO")
    }
  }
}
