/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestRevokeRequestTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestRevokeRequest
    // val modelInstance = RestRevokeRequest()

    // to test the property `tokenId`
    should("test tokenId") {
      // uncomment below to test the property
      // modelInstance.tokenId shouldBe ("TODO")
    }
  }
}
