/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class RestSchedulerActionsResponseTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestSchedulerActionsResponse
    // val modelInstance = RestSchedulerActionsResponse()

    // to test the property `actions`
    should("test actions") {
      // uncomment below to test the property
      // modelInstance.actions shouldBe ("TODO")
    }
  }
}
