/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class ServiceQueryTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of ServiceQuery
    // val modelInstance = ServiceQuery()

    // to test the property `limit`
    should("test limit") {
      // uncomment below to test the property
      // modelInstance.limit shouldBe ("TODO")
    }

    // to test the property `offset`
    should("test offset") {
      // uncomment below to test the property
      // modelInstance.offset shouldBe ("TODO")
    }

    // to test the property `operation`
    should("test operation") {
      // uncomment below to test the property
      // modelInstance.operation shouldBe ("TODO")
    }

    // to test the property `resourcePolicyQuery`
    should("test resourcePolicyQuery") {
      // uncomment below to test the property
      // modelInstance.resourcePolicyQuery shouldBe ("TODO")
    }

    // to test the property `sortDesc`
    should("test sortDesc") {
      // uncomment below to test the property
      // modelInstance.sortDesc shouldBe ("TODO")
    }

    // to test the property `sortField`
    should("test sortField") {
      // uncomment below to test the property
      // modelInstance.sortField shouldBe ("TODO")
    }

    // to test the property `subQueries`
    should("test subQueries") {
      // uncomment below to test the property
      // modelInstance.subQueries shouldBe ("TODO")
    }

    // to test the property `groupBy`
    should("test groupBy") {
      // uncomment below to test the property
      // modelInstance.groupBy shouldBe ("TODO")
    }
  }
}
