/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class TreeNodeTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of TreeNode
    // val modelInstance = TreeNode()

    // to test the property `appearsIn`
    should("test appearsIn") {
      // uncomment below to test the property
      // modelInstance.appearsIn shouldBe ("TODO")
    }

    // to test the property `commits`
    should("test commits") {
      // uncomment below to test the property
      // modelInstance.commits shouldBe ("TODO")
    }

    // to test the property `etag`
    should("test etag") {
      // uncomment below to test the property
      // modelInstance.etag shouldBe ("TODO")
    }

    // to test the property `mtime`
    should("test mtime") {
      // uncomment below to test the property
      // modelInstance.mtime shouldBe ("TODO")
    }

    // to test the property `metaStore`
    should("test metaStore") {
      // uncomment below to test the property
      // modelInstance.metaStore shouldBe ("TODO")
    }

    // to test the property `mode` - Permission mode, like 0777. Stored as string using custom
    // ModeString field.
    should("test mode") {
      // uncomment below to test the property
      // modelInstance.mode shouldBe ("TODO")
    }

    // to test the property `modeString`
    should("test modeString") {
      // uncomment below to test the property
      // modelInstance.modeString shouldBe ("TODO")
    }

    // to test the property `path`
    should("test path") {
      // uncomment below to test the property
      // modelInstance.path shouldBe ("TODO")
    }

    // to test the property `propertySize`
    should("test propertySize") {
      // uncomment below to test the property
      // modelInstance.propertySize shouldBe ("TODO")
    }

    // to test the property `type`
    should("test type") {
      // uncomment below to test the property
      // modelInstance.type shouldBe ("TODO")
    }

    // to test the property `uuid`
    should("test uuid") {
      // uncomment below to test the property
      // modelInstance.uuid shouldBe ("TODO")
    }
  }
}
