/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class TreeSearchFacetTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of TreeSearchFacet
    // val modelInstance = TreeSearchFacet()

    // to test the property `count`
    should("test count") {
      // uncomment below to test the property
      // modelInstance.count shouldBe ("TODO")
    }

    // to test the property `end`
    should("test end") {
      // uncomment below to test the property
      // modelInstance.end shouldBe ("TODO")
    }

    // to test the property `fieldName`
    should("test fieldName") {
      // uncomment below to test the property
      // modelInstance.fieldName shouldBe ("TODO")
    }

    // to test the property `label`
    should("test label") {
      // uncomment below to test the property
      // modelInstance.label shouldBe ("TODO")
    }

    // to test the property `max`
    should("test max") {
      // uncomment below to test the property
      // modelInstance.max shouldBe ("TODO")
    }

    // to test the property `min`
    should("test min") {
      // uncomment below to test the property
      // modelInstance.min shouldBe ("TODO")
    }

    // to test the property `start`
    should("test start") {
      // uncomment below to test the property
      // modelInstance.start shouldBe ("TODO")
    }

    // to test the property `term`
    should("test term") {
      // uncomment below to test the property
      // modelInstance.term shouldBe ("TODO")
    }
  }
}
