/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class TreeVersioningPolicyTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of TreeVersioningPolicy
    // val modelInstance = TreeVersioningPolicy()

    // to test the property `description`
    should("test description") {
      // uncomment below to test the property
      // modelInstance.description shouldBe ("TODO")
    }

    // to test the property `ignoreFilesGreaterThan`
    should("test ignoreFilesGreaterThan") {
      // uncomment below to test the property
      // modelInstance.ignoreFilesGreaterThan shouldBe ("TODO")
    }

    // to test the property `keepPeriods`
    should("test keepPeriods") {
      // uncomment below to test the property
      // modelInstance.keepPeriods shouldBe ("TODO")
    }

    // to test the property `maxSizePerFile`
    should("test maxSizePerFile") {
      // uncomment below to test the property
      // modelInstance.maxSizePerFile shouldBe ("TODO")
    }

    // to test the property `maxTotalSize`
    should("test maxTotalSize") {
      // uncomment below to test the property
      // modelInstance.maxTotalSize shouldBe ("TODO")
    }

    // to test the property `name`
    should("test name") {
      // uncomment below to test the property
      // modelInstance.name shouldBe ("TODO")
    }

    // to test the property `nodeDeletedStrategy`
    should("test nodeDeletedStrategy") {
      // uncomment below to test the property
      // modelInstance.nodeDeletedStrategy shouldBe ("TODO")
    }

    // to test the property `uuid`
    should("test uuid") {
      // uncomment below to test the property
      // modelInstance.uuid shouldBe ("TODO")
    }

    // to test the property `versionsDataSourceBucket`
    should("test versionsDataSourceBucket") {
      // uncomment below to test the property
      // modelInstance.versionsDataSourceBucket shouldBe ("TODO")
    }

    // to test the property `versionsDataSourceName`
    should("test versionsDataSourceName") {
      // uncomment below to test the property
      // modelInstance.versionsDataSourceName shouldBe ("TODO")
    }
  }
}
