/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class TreeListNodesRequestTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of TreeListNodesRequest
    // val modelInstance = TreeListNodesRequest()

    // to test the property `ancestors`
    should("test ancestors") {
      // uncomment below to test the property
      // modelInstance.ancestors shouldBe ("TODO")
    }

    // to test the property `filterType`
    should("test filterType") {
      // uncomment below to test the property
      // modelInstance.filterType shouldBe ("TODO")
    }

    // to test the property `limit`
    should("test limit") {
      // uncomment below to test the property
      // modelInstance.limit shouldBe ("TODO")
    }

    // to test the property `node`
    should("test node") {
      // uncomment below to test the property
      // modelInstance.node shouldBe ("TODO")
    }

    // to test the property `offset`
    should("test offset") {
      // uncomment below to test the property
      // modelInstance.offset shouldBe ("TODO")
    }

    // to test the property `recursive`
    should("test recursive") {
      // uncomment below to test the property
      // modelInstance.recursive shouldBe ("TODO")
    }

    // to test the property `sortDirDesc`
    should("test sortDirDesc") {
      // uncomment below to test the property
      // modelInstance.sortDirDesc shouldBe ("TODO")
    }

    // to test the property `sortField`
    should("test sortField") {
      // uncomment below to test the property
      // modelInstance.sortField shouldBe ("TODO")
    }

    // to test the property `statFlags`
    should("test statFlags") {
      // uncomment below to test the property
      // modelInstance.statFlags shouldBe ("TODO")
    }

    // to test the property `withCommits`
    should("test withCommits") {
      // uncomment below to test the property
      // modelInstance.withCommits shouldBe ("TODO")
    }

    // to test the property `withVersions`
    should("test withVersions") {
      // uncomment below to test the property
      // modelInstance.withVersions shouldBe ("TODO")
    }
  }
}
