/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class TreeReadNodeResponseTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of TreeReadNodeResponse
    // val modelInstance = TreeReadNodeResponse()

    // to test the property `node`
    should("test node") {
      // uncomment below to test the property
      // modelInstance.node shouldBe ("TODO")
    }

    // to test the property `success`
    should("test success") {
      // uncomment below to test the property
      // modelInstance.success shouldBe ("TODO")
    }
  }
}
