/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class UpdateApplyUpdateRequestTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of UpdateApplyUpdateRequest
    // val modelInstance = UpdateApplyUpdateRequest()

    // to test the property `packageName`
    should("test packageName") {
      // uncomment below to test the property
      // modelInstance.packageName shouldBe ("TODO")
    }
  }
}
