/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class UpdateApplyUpdateResponseTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of UpdateApplyUpdateResponse
    // val modelInstance = UpdateApplyUpdateResponse()

    // to test the property `message`
    should("test message") {
      // uncomment below to test the property
      // modelInstance.message shouldBe ("TODO")
    }

    // to test the property `success`
    should("test success") {
      // uncomment below to test the property
      // modelInstance.success shouldBe ("TODO")
    }
  }
}
