/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.model

import io.kotlintest.specs.ShouldSpec

class UpdatePackageTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of UpdatePackage
    // val modelInstance = UpdatePackage()

    // to test the property `binaryArch`
    should("test binaryArch") {
      // uncomment below to test the property
      // modelInstance.binaryArch shouldBe ("TODO")
    }

    // to test the property `binaryChecksum`
    should("test binaryChecksum") {
      // uncomment below to test the property
      // modelInstance.binaryChecksum shouldBe ("TODO")
    }

    // to test the property `binaryHashType`
    should("test binaryHashType") {
      // uncomment below to test the property
      // modelInstance.binaryHashType shouldBe ("TODO")
    }

    // to test the property `binaryOS`
    should("test binaryOS") {
      // uncomment below to test the property
      // modelInstance.binaryOS shouldBe ("TODO")
    }

    // to test the property `binarySignature`
    should("test binarySignature") {
      // uncomment below to test the property
      // modelInstance.binarySignature shouldBe ("TODO")
    }

    // to test the property `binarySize`
    should("test binarySize") {
      // uncomment below to test the property
      // modelInstance.binarySize shouldBe ("TODO")
    }

    // to test the property `binaryURL`
    should("test binaryURL") {
      // uncomment below to test the property
      // modelInstance.binaryURL shouldBe ("TODO")
    }

    // to test the property `changeLog`
    should("test changeLog") {
      // uncomment below to test the property
      // modelInstance.changeLog shouldBe ("TODO")
    }

    // to test the property `description`
    should("test description") {
      // uncomment below to test the property
      // modelInstance.description shouldBe ("TODO")
    }

    // to test the property `isPatch`
    should("test isPatch") {
      // uncomment below to test the property
      // modelInstance.isPatch shouldBe ("TODO")
    }

    // to test the property `label`
    should("test label") {
      // uncomment below to test the property
      // modelInstance.label shouldBe ("TODO")
    }

    // to test the property `license`
    should("test license") {
      // uncomment below to test the property
      // modelInstance.license shouldBe ("TODO")
    }

    // to test the property `packageName`
    should("test packageName") {
      // uncomment below to test the property
      // modelInstance.packageName shouldBe ("TODO")
    }

    // to test the property `patchAlgorithm`
    should("test patchAlgorithm") {
      // uncomment below to test the property
      // modelInstance.patchAlgorithm shouldBe ("TODO")
    }

    // to test the property `releaseDate`
    should("test releaseDate") {
      // uncomment below to test the property
      // modelInstance.releaseDate shouldBe ("TODO")
    }

    // to test the property `serviceName`
    should("test serviceName") {
      // uncomment below to test the property
      // modelInstance.serviceName shouldBe ("TODO")
    }

    // to test the property `status`
    should("test status") {
      // uncomment below to test the property
      // modelInstance.status shouldBe ("TODO")
    }

    // to test the property `version`
    should("test version") {
      // uncomment below to test the property
      // modelInstance.version shouldBe ("TODO")
    }
  }
}
