/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.pydio.kotlin.openapi.v2.moshi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.pydio.kotlin.openapi.v2.moshi.model.JobsCtrlCommand
import com.pydio.kotlin.openapi.v2.moshi.model.JobsCommand

class JobsCtrlCommandTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of JobsCtrlCommand
        //val modelInstance = JobsCtrlCommand()

        // to test the property `cmd`
        should("test cmd") {
            // uncomment below to test the property
            //modelInstance.cmd shouldBe ("TODO")
        }

        // to test the property `jobId`
        should("test jobId") {
            // uncomment below to test the property
            //modelInstance.jobId shouldBe ("TODO")
        }

        // to test the property `ownerId`
        should("test ownerId") {
            // uncomment below to test the property
            //modelInstance.ownerId shouldBe ("TODO")
        }

        // to test the property `runParameters`
        should("test runParameters") {
            // uncomment below to test the property
            //modelInstance.runParameters shouldBe ("TODO")
        }

        // to test the property `taskId`
        should("test taskId") {
            // uncomment below to test the property
            //modelInstance.taskId shouldBe ("TODO")
        }

    }
}
