/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.pydio.kotlin.openapi.v2.moshi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.pydio.kotlin.openapi.v2.moshi.model.RestMetaUpdate
import com.pydio.kotlin.openapi.v2.moshi.model.MetaUpdateOp
import com.pydio.kotlin.openapi.v2.moshi.model.RestUserMeta

class RestMetaUpdateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RestMetaUpdate
        //val modelInstance = RestMetaUpdate()

        // to test the property `operation`
        should("test operation") {
            // uncomment below to test the property
            //modelInstance.operation shouldBe ("TODO")
        }

        // to test the property `userMeta`
        should("test userMeta") {
            // uncomment below to test the property
            //modelInstance.userMeta shouldBe ("TODO")
        }

    }
}
