/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.v2.moshi.model

import io.kotlintest.specs.ShouldSpec

class RestSelectionTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestSelection
    // val modelInstance = RestSelection()

    // to test the property `nodes`
    should("test nodes") {
      // uncomment below to test the property
      // modelInstance.nodes shouldBe ("TODO")
    }

    // to test the property `uuid`
    should("test uuid") {
      // uncomment below to test the property
      // modelInstance.uuid shouldBe ("TODO")
    }
  }
}
