/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.pydio.kotlin.openapi.v2.moshi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.pydio.kotlin.openapi.v2.moshi.model.RestCreateCheckRequest
import com.pydio.kotlin.openapi.v2.moshi.model.RestIncomingNode

class RestCreateCheckRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RestCreateCheckRequest
        //val modelInstance = RestCreateCheckRequest()

        // to test the property `inputs`
        should("test inputs") {
            // uncomment below to test the property
            //modelInstance.inputs shouldBe ("TODO")
        }

        // to test the property `findAvailablePath`
        should("test findAvailablePath") {
            // uncomment below to test the property
            //modelInstance.findAvailablePath shouldBe ("TODO")
        }

    }
}
