/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.pydio.kotlin.openapi.v2.moshi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.pydio.kotlin.openapi.v2.moshi.model.RestCreateCheckResponse
import com.pydio.kotlin.openapi.v2.moshi.model.RestCheckResult

class RestCreateCheckResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RestCreateCheckResponse
        //val modelInstance = RestCreateCheckResponse()

        // to test the property `results`
        should("test results") {
            // uncomment below to test the property
            //modelInstance.results shouldBe ("TODO")
        }

    }
}
