/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.v2.moshi.model

import io.kotlintest.specs.ShouldSpec

class RestPublicLinkRequestTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestPublicLinkRequest
    // val modelInstance = RestPublicLinkRequest()

    // to test the property `link`
    should("test link") {
      // uncomment below to test the property
      // modelInstance.link shouldBe ("TODO")
    }

    // to test the property `createPassword`
    should("test createPassword") {
      // uncomment below to test the property
      // modelInstance.createPassword shouldBe ("TODO")
    }

    // to test the property `passwordEnabled`
    should("test passwordEnabled") {
      // uncomment below to test the property
      // modelInstance.passwordEnabled shouldBe ("TODO")
    }

    // to test the property `updateCustomHash`
    should("test updateCustomHash") {
      // uncomment below to test the property
      // modelInstance.updateCustomHash shouldBe ("TODO")
    }

    // to test the property `updatePassword`
    should("test updatePassword") {
      // uncomment below to test the property
      // modelInstance.updatePassword shouldBe ("TODO")
    }
  }
}
