/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.v2.moshi.model

import io.kotlintest.specs.ShouldSpec

class TreeNodeChangeEventTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of TreeNodeChangeEvent
    // val modelInstance = TreeNodeChangeEvent()

    // to test the property `metadata`
    should("test metadata") {
      // uncomment below to test the property
      // modelInstance.metadata shouldBe ("TODO")
    }

    // to test the property `optimistic`
    should("test optimistic") {
      // uncomment below to test the property
      // modelInstance.optimistic shouldBe ("TODO")
    }

    // to test the property `silent`
    should("test silent") {
      // uncomment below to test the property
      // modelInstance.silent shouldBe ("TODO")
    }

    // to test the property `source`
    should("test source") {
      // uncomment below to test the property
      // modelInstance.source shouldBe ("TODO")
    }

    // to test the property `target`
    should("test target") {
      // uncomment below to test the property
      // modelInstance.target shouldBe ("TODO")
    }

    // to test the property `type`
    should("test type") {
      // uncomment below to test the property
      // modelInstance.type shouldBe ("TODO")
    }
  }
}
