/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.pydio.kotlin.openapi.v2.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.pydio.kotlin.openapi.v2.model.RestNodeLocators
import com.pydio.kotlin.openapi.v2.model.RestNodeLocator

class RestNodeLocatorsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RestNodeLocators
        //val modelInstance = RestNodeLocators()

        // to test the property `many`
        should("test many") {
            // uncomment below to test the property
            //modelInstance.many shouldBe ("TODO")
        }

    }
}
