/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.v2.model

import io.kotlintest.specs.ShouldSpec

class RestNamespaceValuesOperationTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestNamespaceValuesOperation
    // val modelInstance = RestNamespaceValuesOperation()

    // to test the property `operation`
    should("test operation") {
      // uncomment below to test the property
      // modelInstance.operation shouldBe ("TODO")
    }

    // to test the property `propertyValues`
    should("test propertyValues") {
      // uncomment below to test the property
      // modelInstance.propertyValues shouldBe ("TODO")
    }
  }
}
