/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.v2.model

import io.kotlintest.specs.ShouldSpec

class RestCheckResultTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestCheckResult
    // val modelInstance = RestCheckResult()

    // to test the property `exists`
    should("test exists") {
      // uncomment below to test the property
      // modelInstance.exists shouldBe ("TODO")
    }

    // to test the property `inputLocator`
    should("test inputLocator") {
      // uncomment below to test the property
      // modelInstance.inputLocator shouldBe ("TODO")
    }

    // to test the property `nextPath`
    should("test nextPath") {
      // uncomment below to test the property
      // modelInstance.nextPath shouldBe ("TODO")
    }

    // to test the property `node`
    should("test node") {
      // uncomment below to test the property
      // modelInstance.node shouldBe ("TODO")
    }
  }
}
