/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.v2.model

import io.kotlintest.specs.ShouldSpec

class RestCreateCheckResponseTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestCreateCheckResponse
    // val modelInstance = RestCreateCheckResponse()

    // to test the property `results`
    should("test results") {
      // uncomment below to test the property
      // modelInstance.results shouldBe ("TODO")
    }
  }
}
