/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.v2.model

import io.kotlintest.specs.ShouldSpec

class RestListTemplatesResponseTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestListTemplatesResponse
    // val modelInstance = RestListTemplatesResponse()

    // to test the property `templates`
    should("test templates") {
      // uncomment below to test the property
      // modelInstance.templates shouldBe ("TODO")
    }
  }
}
