/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.pydio.kotlin.openapi.v2.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.pydio.kotlin.openapi.v2.model.RestLookupRequest
import com.pydio.kotlin.openapi.v2.model.RestNodeLocators
import com.pydio.kotlin.openapi.v2.model.TreeQuery

class RestLookupRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RestLookupRequest
        //val modelInstance = RestLookupRequest()

        // to test the property `limit`
        should("test limit") {
            // uncomment below to test the property
            //modelInstance.limit shouldBe ("TODO")
        }

        // to test the property `locators`
        should("test locators") {
            // uncomment below to test the property
            //modelInstance.locators shouldBe ("TODO")
        }

        // to test the property `offset`
        should("test offset") {
            // uncomment below to test the property
            //modelInstance.offset shouldBe ("TODO")
        }

        // to test the property `query`
        should("test query") {
            // uncomment below to test the property
            //modelInstance.query shouldBe ("TODO")
        }

        // to test the property `sortDirDesc`
        should("test sortDirDesc") {
            // uncomment below to test the property
            //modelInstance.sortDirDesc shouldBe ("TODO")
        }

        // to test the property `sortField`
        should("test sortField") {
            // uncomment below to test the property
            //modelInstance.sortField shouldBe ("TODO")
        }

        // to test the property `statFlags`
        should("test statFlags") {
            // uncomment below to test the property
            //modelInstance.statFlags shouldBe ("TODO")
        }

    }
}
