/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.v2.model

import io.kotlintest.specs.ShouldSpec

class RestBackgroundActionTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestBackgroundAction
    // val modelInstance = RestBackgroundAction()

    // to test the property `jobUuid`
    should("test jobUuid") {
      // uncomment below to test the property
      // modelInstance.jobUuid shouldBe ("TODO")
    }

    // to test the property `name`
    should("test name") {
      // uncomment below to test the property
      // modelInstance.name shouldBe ("TODO")
    }

    // to test the property `canPause`
    should("test canPause") {
      // uncomment below to test the property
      // modelInstance.canPause shouldBe ("TODO")
    }

    // to test the property `canStop`
    should("test canStop") {
      // uncomment below to test the property
      // modelInstance.canStop shouldBe ("TODO")
    }

    // to test the property `endTime`
    should("test endTime") {
      // uncomment below to test the property
      // modelInstance.endTime shouldBe ("TODO")
    }

    // to test the property `hasProgress`
    should("test hasProgress") {
      // uncomment below to test the property
      // modelInstance.hasProgress shouldBe ("TODO")
    }

    // to test the property `label`
    should("test label") {
      // uncomment below to test the property
      // modelInstance.label shouldBe ("TODO")
    }

    // to test the property `progress`
    should("test progress") {
      // uncomment below to test the property
      // modelInstance.progress shouldBe ("TODO")
    }

    // to test the property `startTime`
    should("test startTime") {
      // uncomment below to test the property
      // modelInstance.startTime shouldBe ("TODO")
    }

    // to test the property `status`
    should("test status") {
      // uncomment below to test the property
      // modelInstance.status shouldBe ("TODO")
    }

    // to test the property `statusMessage`
    should("test statusMessage") {
      // uncomment below to test the property
      // modelInstance.statusMessage shouldBe ("TODO")
    }
  }
}
