/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.v2.model

import io.kotlintest.specs.ShouldSpec

class RestUserMetaTest : ShouldSpec() {
  init {
    // uncomment below to create an instance of RestUserMeta
    // val modelInstance = RestUserMeta()

    // to test the property `jsonValue`
    should("test jsonValue") {
      // uncomment below to test the property
      // modelInstance.jsonValue shouldBe ("TODO")
    }

    // to test the property `namespace`
    should("test namespace") {
      // uncomment below to test the property
      // modelInstance.namespace shouldBe ("TODO")
    }

    // to test the property `editable`
    should("test editable") {
      // uncomment below to test the property
      // modelInstance.editable shouldBe ("TODO")
    }

    // to test the property `nodeUuid`
    should("test nodeUuid") {
      // uncomment below to test the property
      // modelInstance.nodeUuid shouldBe ("TODO")
    }
  }
}
