/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.v2.model

import com.squareup.moshi.Json

/**
 * @param operation
 * @param userMeta
 */
data class RestMetaUpdate(
    @Json(name = "Operation") val operation: MetaUpdateOp = MetaUpdateOp.PUT,
    @Json(name = "UserMeta") val userMeta: RestUserMeta
) {}
