/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.v2.model

import com.squareup.moshi.Json

/**
 * @param awaitStatus
 * @param awaitTimeout
 * @param jsonParameters
 * @param nodes
 * @param selectionUuid
 * @param targetNode
 */
data class RestActionParameters(
    @Json(name = "AwaitStatus") val awaitStatus: JobsTaskStatus? = JobsTaskStatus.Unknown,
    @Json(name = "AwaitTimeout") val awaitTimeout: kotlin.String? = null,
    @Json(name = "JsonParameters") val jsonParameters: kotlin.String? = null,
    @Json(name = "Nodes") val nodes: kotlin.collections.List<RestNodeLocator>? = null,
    @Json(name = "SelectionUuid") val selectionUuid: kotlin.String? = null,
    @Json(name = "TargetNode") val targetNode: RestNodeLocator? = null
) {}
