/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.pydio.kotlin.openapi.v2.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param namespace 
 * @param `value` 
 */


data class RestCountMeta (

    @Json(name = "Namespace")
    val namespace: kotlin.String,

    @Json(name = "Value")
    val `value`: kotlin.Int

) {


}

