/**
 * Please note: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
@file:Suppress("ArrayInDataClass", "EnumEntryName", "RemoveRedundantQualifierName", "UnusedImport")

package com.pydio.kotlin.openapi.v2.model

import com.squareup.moshi.Json

/**
 * @param bookmark
 * @param contentLock
 * @param metaUpdates
 */
data class RestNodeUpdates(
    @Json(name = "Bookmark") val bookmark: RestMetaToggle? = null,
    @Json(name = "ContentLock") val contentLock: RestMetaToggle? = null,
    @Json(name = "MetaUpdates") val metaUpdates: kotlin.collections.List<RestMetaUpdate>? = null
) {}
