/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.pydio.kotlin.openapi.v2.model

import com.pydio.kotlin.openapi.v2.model.RestIncomingNode

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Request for pre-checking nodes before uploading or creating them.
 *
 * @param inputs 
 * @param findAvailablePath 
 */


data class RestCreateCheckRequest (

    @Json(name = "Inputs")
    val inputs: kotlin.collections.List<RestIncomingNode>,

    @Json(name = "FindAvailablePath")
    val findAvailablePath: kotlin.Boolean? = null

) {


}

